// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/simple.dart';
import 'api/svg.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  SvgBlur dco_decode_box_autoadd_svg_blur(dynamic raw);

  @protected
  SvgEffects dco_decode_box_autoadd_svg_effects(dynamic raw);

  @protected
  SvgGradient dco_decode_box_autoadd_svg_gradient(dynamic raw);

  @protected
  SvgMask dco_decode_box_autoadd_svg_mask(dynamic raw);

  @protected
  SvgPattern dco_decode_box_autoadd_svg_pattern(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SvgClip> dco_decode_list_svg_clip(dynamic raw);

  @protected
  List<SvgGradientStop> dco_decode_list_svg_gradient_stop(dynamic raw);

  @protected
  List<SvgImage> dco_decode_list_svg_image(dynamic raw);

  @protected
  List<SvgPath> dco_decode_list_svg_path(dynamic raw);

  @protected
  SvgBlur? dco_decode_opt_box_autoadd_svg_blur(dynamic raw);

  @protected
  SvgEffects? dco_decode_opt_box_autoadd_svg_effects(dynamic raw);

  @protected
  SvgGradient? dco_decode_opt_box_autoadd_svg_gradient(dynamic raw);

  @protected
  SvgMask? dco_decode_opt_box_autoadd_svg_mask(dynamic raw);

  @protected
  SvgPattern? dco_decode_opt_box_autoadd_svg_pattern(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  Float32List? dco_decode_opt_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  SvgBlur dco_decode_svg_blur(dynamic raw);

  @protected
  SvgClip dco_decode_svg_clip(dynamic raw);

  @protected
  SvgEffects dco_decode_svg_effects(dynamic raw);

  @protected
  SvgGradient dco_decode_svg_gradient(dynamic raw);

  @protected
  SvgGradientStop dco_decode_svg_gradient_stop(dynamic raw);

  @protected
  SvgImage dco_decode_svg_image(dynamic raw);

  @protected
  SvgImageFormat dco_decode_svg_image_format(dynamic raw);

  @protected
  SvgMask dco_decode_svg_mask(dynamic raw);

  @protected
  SvgPath dco_decode_svg_path(dynamic raw);

  @protected
  SvgPattern dco_decode_svg_pattern(dynamic raw);

  @protected
  SvgScene dco_decode_svg_scene(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  SvgBlur sse_decode_box_autoadd_svg_blur(SseDeserializer deserializer);

  @protected
  SvgEffects sse_decode_box_autoadd_svg_effects(SseDeserializer deserializer);

  @protected
  SvgGradient sse_decode_box_autoadd_svg_gradient(SseDeserializer deserializer);

  @protected
  SvgMask sse_decode_box_autoadd_svg_mask(SseDeserializer deserializer);

  @protected
  SvgPattern sse_decode_box_autoadd_svg_pattern(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SvgClip> sse_decode_list_svg_clip(SseDeserializer deserializer);

  @protected
  List<SvgGradientStop> sse_decode_list_svg_gradient_stop(
    SseDeserializer deserializer,
  );

  @protected
  List<SvgImage> sse_decode_list_svg_image(SseDeserializer deserializer);

  @protected
  List<SvgPath> sse_decode_list_svg_path(SseDeserializer deserializer);

  @protected
  SvgBlur? sse_decode_opt_box_autoadd_svg_blur(SseDeserializer deserializer);

  @protected
  SvgEffects? sse_decode_opt_box_autoadd_svg_effects(
    SseDeserializer deserializer,
  );

  @protected
  SvgGradient? sse_decode_opt_box_autoadd_svg_gradient(
    SseDeserializer deserializer,
  );

  @protected
  SvgMask? sse_decode_opt_box_autoadd_svg_mask(SseDeserializer deserializer);

  @protected
  SvgPattern? sse_decode_opt_box_autoadd_svg_pattern(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Float32List? sse_decode_opt_list_prim_f_32_strict(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  SvgBlur sse_decode_svg_blur(SseDeserializer deserializer);

  @protected
  SvgClip sse_decode_svg_clip(SseDeserializer deserializer);

  @protected
  SvgEffects sse_decode_svg_effects(SseDeserializer deserializer);

  @protected
  SvgGradient sse_decode_svg_gradient(SseDeserializer deserializer);

  @protected
  SvgGradientStop sse_decode_svg_gradient_stop(SseDeserializer deserializer);

  @protected
  SvgImage sse_decode_svg_image(SseDeserializer deserializer);

  @protected
  SvgImageFormat sse_decode_svg_image_format(SseDeserializer deserializer);

  @protected
  SvgMask sse_decode_svg_mask(SseDeserializer deserializer);

  @protected
  SvgPath sse_decode_svg_path(SseDeserializer deserializer);

  @protected
  SvgPattern sse_decode_svg_pattern(SseDeserializer deserializer);

  @protected
  SvgScene sse_decode_svg_scene(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_svg_blur(SvgBlur self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_svg_effects(
    SvgEffects self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_svg_gradient(
    SvgGradient self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_svg_mask(SvgMask self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_svg_pattern(
    SvgPattern self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_svg_clip(List<SvgClip> self, SseSerializer serializer);

  @protected
  void sse_encode_list_svg_gradient_stop(
    List<SvgGradientStop> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_svg_image(List<SvgImage> self, SseSerializer serializer);

  @protected
  void sse_encode_list_svg_path(List<SvgPath> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_svg_blur(
    SvgBlur? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_svg_effects(
    SvgEffects? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_svg_gradient(
    SvgGradient? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_svg_mask(
    SvgMask? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_svg_pattern(
    SvgPattern? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_f_32_strict(
    Float32List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_svg_blur(SvgBlur self, SseSerializer serializer);

  @protected
  void sse_encode_svg_clip(SvgClip self, SseSerializer serializer);

  @protected
  void sse_encode_svg_effects(SvgEffects self, SseSerializer serializer);

  @protected
  void sse_encode_svg_gradient(SvgGradient self, SseSerializer serializer);

  @protected
  void sse_encode_svg_gradient_stop(
    SvgGradientStop self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_svg_image(SvgImage self, SseSerializer serializer);

  @protected
  void sse_encode_svg_image_format(
    SvgImageFormat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_svg_mask(SvgMask self, SseSerializer serializer);

  @protected
  void sse_encode_svg_path(SvgPath self, SseSerializer serializer);

  @protected
  void sse_encode_svg_pattern(SvgPattern self, SseSerializer serializer);

  @protected
  void sse_encode_svg_scene(SvgScene self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
