// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'api/svg.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -705259901;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'fsvg',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Uint8List? crateApiSvgParseColor({required String s});

  SvgScene crateApiSvgParseSvg({required String data, int? currentColor});

  Float32List? crateApiSvgParseTransform({required String s});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Uint8List? crateApiSvgParseColor({required String s}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(s, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSvgParseColorConstMeta,
        argValues: [s],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSvgParseColorConstMeta =>
      const TaskConstMeta(debugName: "parse_color", argNames: ["s"]);

  @override
  SvgScene crateApiSvgParseSvg({required String data, int? currentColor}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(data, serializer);
          sse_encode_opt_box_autoadd_u_32(currentColor, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_svg_scene,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSvgParseSvgConstMeta,
        argValues: [data, currentColor],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSvgParseSvgConstMeta => const TaskConstMeta(
    debugName: "parse_svg",
    argNames: ["data", "currentColor"],
  );

  @override
  Float32List? crateApiSvgParseTransform({required String s}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(s, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_f_32_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSvgParseTransformConstMeta,
        argValues: [s],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSvgParseTransformConstMeta =>
      const TaskConstMeta(debugName: "parse_transform", argNames: ["s"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  SvgBlur dco_decode_box_autoadd_svg_blur(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_svg_blur(raw);
  }

  @protected
  SvgEffects dco_decode_box_autoadd_svg_effects(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_svg_effects(raw);
  }

  @protected
  SvgGradient dco_decode_box_autoadd_svg_gradient(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_svg_gradient(raw);
  }

  @protected
  SvgMask dco_decode_box_autoadd_svg_mask(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_svg_mask(raw);
  }

  @protected
  SvgPattern dco_decode_box_autoadd_svg_pattern(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_svg_pattern(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SvgClip> dco_decode_list_svg_clip(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_svg_clip).toList();
  }

  @protected
  List<SvgGradientStop> dco_decode_list_svg_gradient_stop(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_svg_gradient_stop).toList();
  }

  @protected
  List<SvgImage> dco_decode_list_svg_image(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_svg_image).toList();
  }

  @protected
  List<SvgPath> dco_decode_list_svg_path(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_svg_path).toList();
  }

  @protected
  SvgBlur? dco_decode_opt_box_autoadd_svg_blur(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_svg_blur(raw);
  }

  @protected
  SvgEffects? dco_decode_opt_box_autoadd_svg_effects(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_svg_effects(raw);
  }

  @protected
  SvgGradient? dco_decode_opt_box_autoadd_svg_gradient(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_svg_gradient(raw);
  }

  @protected
  SvgMask? dco_decode_opt_box_autoadd_svg_mask(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_svg_mask(raw);
  }

  @protected
  SvgPattern? dco_decode_opt_box_autoadd_svg_pattern(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_svg_pattern(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  Float32List? dco_decode_opt_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_f_32_strict(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  SvgBlur dco_decode_svg_blur(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SvgBlur(
      stdDevX: dco_decode_f_32(arr[0]),
      stdDevY: dco_decode_f_32(arr[1]),
    );
  }

  @protected
  SvgClip dco_decode_svg_clip(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SvgClip(
      verbs: dco_decode_list_prim_u_8_strict(arr[0]),
      points: dco_decode_list_prim_f_32_strict(arr[1]),
      evenOdd: dco_decode_bool(arr[2]),
    );
  }

  @protected
  SvgEffects dco_decode_svg_effects(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SvgEffects(
      fillPattern: dco_decode_opt_box_autoadd_svg_pattern(arr[0]),
      strokePattern: dco_decode_opt_box_autoadd_svg_pattern(arr[1]),
      clips: dco_decode_list_svg_clip(arr[2]),
      mask: dco_decode_opt_box_autoadd_svg_mask(arr[3]),
      blur: dco_decode_opt_box_autoadd_svg_blur(arr[4]),
    );
  }

  @protected
  SvgGradient dco_decode_svg_gradient(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return SvgGradient(
      kind: dco_decode_u_8(arr[0]),
      x1: dco_decode_f_32(arr[1]),
      y1: dco_decode_f_32(arr[2]),
      x2: dco_decode_f_32(arr[3]),
      y2: dco_decode_f_32(arr[4]),
      radius: dco_decode_f_32(arr[5]),
      matrix: dco_decode_list_prim_f_32_strict(arr[6]),
      stops: dco_decode_list_svg_gradient_stop(arr[7]),
      spread: dco_decode_u_8(arr[8]),
    );
  }

  @protected
  SvgGradientStop dco_decode_svg_gradient_stop(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SvgGradientStop(
      offset: dco_decode_f_32(arr[0]),
      colorArgb: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  SvgImage dco_decode_svg_image(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return SvgImage(
      x: dco_decode_f_32(arr[0]),
      y: dco_decode_f_32(arr[1]),
      width: dco_decode_f_32(arr[2]),
      height: dco_decode_f_32(arr[3]),
      data: dco_decode_list_prim_u_8_strict(arr[4]),
      format: dco_decode_svg_image_format(arr[5]),
    );
  }

  @protected
  SvgImageFormat dco_decode_svg_image_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SvgImageFormat.values[raw as int];
  }

  @protected
  SvgMask dco_decode_svg_mask(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return SvgMask(
      kind: dco_decode_u_8(arr[0]),
      x: dco_decode_f_32(arr[1]),
      y: dco_decode_f_32(arr[2]),
      width: dco_decode_f_32(arr[3]),
      height: dco_decode_f_32(arr[4]),
      paths: dco_decode_list_svg_path(arr[5]),
    );
  }

  @protected
  SvgPath dco_decode_svg_path(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return SvgPath(
      verbs: dco_decode_list_prim_u_8_strict(arr[0]),
      points: dco_decode_list_prim_f_32_strict(arr[1]),
      hasFill: dco_decode_bool(arr[2]),
      fillArgb: dco_decode_u_32(arr[3]),
      evenOdd: dco_decode_bool(arr[4]),
      hasStroke: dco_decode_bool(arr[5]),
      strokeArgb: dco_decode_u_32(arr[6]),
      strokeWidth: dco_decode_f_32(arr[7]),
      strokeFirst: dco_decode_bool(arr[8]),
      fillGradient: dco_decode_opt_box_autoadd_svg_gradient(arr[9]),
      strokeGradient: dco_decode_opt_box_autoadd_svg_gradient(arr[10]),
      effects: dco_decode_opt_box_autoadd_svg_effects(arr[11]),
    );
  }

  @protected
  SvgPattern dco_decode_svg_pattern(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return SvgPattern(
      x: dco_decode_f_32(arr[0]),
      y: dco_decode_f_32(arr[1]),
      width: dco_decode_f_32(arr[2]),
      height: dco_decode_f_32(arr[3]),
      matrix: dco_decode_list_prim_f_32_strict(arr[4]),
      paths: dco_decode_list_svg_path(arr[5]),
    );
  }

  @protected
  SvgScene dco_decode_svg_scene(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SvgScene(
      width: dco_decode_f_32(arr[0]),
      height: dco_decode_f_32(arr[1]),
      paths: dco_decode_list_svg_path(arr[2]),
      images: dco_decode_list_svg_image(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  SvgBlur sse_decode_box_autoadd_svg_blur(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_svg_blur(deserializer));
  }

  @protected
  SvgEffects sse_decode_box_autoadd_svg_effects(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_svg_effects(deserializer));
  }

  @protected
  SvgGradient sse_decode_box_autoadd_svg_gradient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_svg_gradient(deserializer));
  }

  @protected
  SvgMask sse_decode_box_autoadd_svg_mask(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_svg_mask(deserializer));
  }

  @protected
  SvgPattern sse_decode_box_autoadd_svg_pattern(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_svg_pattern(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SvgClip> sse_decode_list_svg_clip(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SvgClip>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_svg_clip(deserializer));
    }
    return ans_;
  }

  @protected
  List<SvgGradientStop> sse_decode_list_svg_gradient_stop(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SvgGradientStop>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_svg_gradient_stop(deserializer));
    }
    return ans_;
  }

  @protected
  List<SvgImage> sse_decode_list_svg_image(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SvgImage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_svg_image(deserializer));
    }
    return ans_;
  }

  @protected
  List<SvgPath> sse_decode_list_svg_path(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SvgPath>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_svg_path(deserializer));
    }
    return ans_;
  }

  @protected
  SvgBlur? sse_decode_opt_box_autoadd_svg_blur(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_svg_blur(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SvgEffects? sse_decode_opt_box_autoadd_svg_effects(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_svg_effects(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SvgGradient? sse_decode_opt_box_autoadd_svg_gradient(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_svg_gradient(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SvgMask? sse_decode_opt_box_autoadd_svg_mask(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_svg_mask(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SvgPattern? sse_decode_opt_box_autoadd_svg_pattern(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_svg_pattern(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Float32List? sse_decode_opt_list_prim_f_32_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_f_32_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SvgBlur sse_decode_svg_blur(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_stdDevX = sse_decode_f_32(deserializer);
    var var_stdDevY = sse_decode_f_32(deserializer);
    return SvgBlur(stdDevX: var_stdDevX, stdDevY: var_stdDevY);
  }

  @protected
  SvgClip sse_decode_svg_clip(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_verbs = sse_decode_list_prim_u_8_strict(deserializer);
    var var_points = sse_decode_list_prim_f_32_strict(deserializer);
    var var_evenOdd = sse_decode_bool(deserializer);
    return SvgClip(verbs: var_verbs, points: var_points, evenOdd: var_evenOdd);
  }

  @protected
  SvgEffects sse_decode_svg_effects(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fillPattern = sse_decode_opt_box_autoadd_svg_pattern(deserializer);
    var var_strokePattern = sse_decode_opt_box_autoadd_svg_pattern(
      deserializer,
    );
    var var_clips = sse_decode_list_svg_clip(deserializer);
    var var_mask = sse_decode_opt_box_autoadd_svg_mask(deserializer);
    var var_blur = sse_decode_opt_box_autoadd_svg_blur(deserializer);
    return SvgEffects(
      fillPattern: var_fillPattern,
      strokePattern: var_strokePattern,
      clips: var_clips,
      mask: var_mask,
      blur: var_blur,
    );
  }

  @protected
  SvgGradient sse_decode_svg_gradient(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_u_8(deserializer);
    var var_x1 = sse_decode_f_32(deserializer);
    var var_y1 = sse_decode_f_32(deserializer);
    var var_x2 = sse_decode_f_32(deserializer);
    var var_y2 = sse_decode_f_32(deserializer);
    var var_radius = sse_decode_f_32(deserializer);
    var var_matrix = sse_decode_list_prim_f_32_strict(deserializer);
    var var_stops = sse_decode_list_svg_gradient_stop(deserializer);
    var var_spread = sse_decode_u_8(deserializer);
    return SvgGradient(
      kind: var_kind,
      x1: var_x1,
      y1: var_y1,
      x2: var_x2,
      y2: var_y2,
      radius: var_radius,
      matrix: var_matrix,
      stops: var_stops,
      spread: var_spread,
    );
  }

  @protected
  SvgGradientStop sse_decode_svg_gradient_stop(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_offset = sse_decode_f_32(deserializer);
    var var_colorArgb = sse_decode_u_32(deserializer);
    return SvgGradientStop(offset: var_offset, colorArgb: var_colorArgb);
  }

  @protected
  SvgImage sse_decode_svg_image(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_x = sse_decode_f_32(deserializer);
    var var_y = sse_decode_f_32(deserializer);
    var var_width = sse_decode_f_32(deserializer);
    var var_height = sse_decode_f_32(deserializer);
    var var_data = sse_decode_list_prim_u_8_strict(deserializer);
    var var_format = sse_decode_svg_image_format(deserializer);
    return SvgImage(
      x: var_x,
      y: var_y,
      width: var_width,
      height: var_height,
      data: var_data,
      format: var_format,
    );
  }

  @protected
  SvgImageFormat sse_decode_svg_image_format(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SvgImageFormat.values[inner];
  }

  @protected
  SvgMask sse_decode_svg_mask(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_u_8(deserializer);
    var var_x = sse_decode_f_32(deserializer);
    var var_y = sse_decode_f_32(deserializer);
    var var_width = sse_decode_f_32(deserializer);
    var var_height = sse_decode_f_32(deserializer);
    var var_paths = sse_decode_list_svg_path(deserializer);
    return SvgMask(
      kind: var_kind,
      x: var_x,
      y: var_y,
      width: var_width,
      height: var_height,
      paths: var_paths,
    );
  }

  @protected
  SvgPath sse_decode_svg_path(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_verbs = sse_decode_list_prim_u_8_strict(deserializer);
    var var_points = sse_decode_list_prim_f_32_strict(deserializer);
    var var_hasFill = sse_decode_bool(deserializer);
    var var_fillArgb = sse_decode_u_32(deserializer);
    var var_evenOdd = sse_decode_bool(deserializer);
    var var_hasStroke = sse_decode_bool(deserializer);
    var var_strokeArgb = sse_decode_u_32(deserializer);
    var var_strokeWidth = sse_decode_f_32(deserializer);
    var var_strokeFirst = sse_decode_bool(deserializer);
    var var_fillGradient = sse_decode_opt_box_autoadd_svg_gradient(
      deserializer,
    );
    var var_strokeGradient = sse_decode_opt_box_autoadd_svg_gradient(
      deserializer,
    );
    var var_effects = sse_decode_opt_box_autoadd_svg_effects(deserializer);
    return SvgPath(
      verbs: var_verbs,
      points: var_points,
      hasFill: var_hasFill,
      fillArgb: var_fillArgb,
      evenOdd: var_evenOdd,
      hasStroke: var_hasStroke,
      strokeArgb: var_strokeArgb,
      strokeWidth: var_strokeWidth,
      strokeFirst: var_strokeFirst,
      fillGradient: var_fillGradient,
      strokeGradient: var_strokeGradient,
      effects: var_effects,
    );
  }

  @protected
  SvgPattern sse_decode_svg_pattern(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_x = sse_decode_f_32(deserializer);
    var var_y = sse_decode_f_32(deserializer);
    var var_width = sse_decode_f_32(deserializer);
    var var_height = sse_decode_f_32(deserializer);
    var var_matrix = sse_decode_list_prim_f_32_strict(deserializer);
    var var_paths = sse_decode_list_svg_path(deserializer);
    return SvgPattern(
      x: var_x,
      y: var_y,
      width: var_width,
      height: var_height,
      matrix: var_matrix,
      paths: var_paths,
    );
  }

  @protected
  SvgScene sse_decode_svg_scene(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_f_32(deserializer);
    var var_height = sse_decode_f_32(deserializer);
    var var_paths = sse_decode_list_svg_path(deserializer);
    var var_images = sse_decode_list_svg_image(deserializer);
    return SvgScene(
      width: var_width,
      height: var_height,
      paths: var_paths,
      images: var_images,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_svg_blur(SvgBlur self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_svg_blur(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_svg_effects(
    SvgEffects self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_svg_effects(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_svg_gradient(
    SvgGradient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_svg_gradient(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_svg_mask(SvgMask self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_svg_mask(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_svg_pattern(
    SvgPattern self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_svg_pattern(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_svg_clip(List<SvgClip> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_svg_clip(item, serializer);
    }
  }

  @protected
  void sse_encode_list_svg_gradient_stop(
    List<SvgGradientStop> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_svg_gradient_stop(item, serializer);
    }
  }

  @protected
  void sse_encode_list_svg_image(
    List<SvgImage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_svg_image(item, serializer);
    }
  }

  @protected
  void sse_encode_list_svg_path(List<SvgPath> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_svg_path(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_svg_blur(
    SvgBlur? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_svg_blur(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_svg_effects(
    SvgEffects? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_svg_effects(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_svg_gradient(
    SvgGradient? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_svg_gradient(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_svg_mask(
    SvgMask? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_svg_mask(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_svg_pattern(
    SvgPattern? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_svg_pattern(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_f_32_strict(
    Float32List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_f_32_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_svg_blur(SvgBlur self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.stdDevX, serializer);
    sse_encode_f_32(self.stdDevY, serializer);
  }

  @protected
  void sse_encode_svg_clip(SvgClip self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.verbs, serializer);
    sse_encode_list_prim_f_32_strict(self.points, serializer);
    sse_encode_bool(self.evenOdd, serializer);
  }

  @protected
  void sse_encode_svg_effects(SvgEffects self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_svg_pattern(self.fillPattern, serializer);
    sse_encode_opt_box_autoadd_svg_pattern(self.strokePattern, serializer);
    sse_encode_list_svg_clip(self.clips, serializer);
    sse_encode_opt_box_autoadd_svg_mask(self.mask, serializer);
    sse_encode_opt_box_autoadd_svg_blur(self.blur, serializer);
  }

  @protected
  void sse_encode_svg_gradient(SvgGradient self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.kind, serializer);
    sse_encode_f_32(self.x1, serializer);
    sse_encode_f_32(self.y1, serializer);
    sse_encode_f_32(self.x2, serializer);
    sse_encode_f_32(self.y2, serializer);
    sse_encode_f_32(self.radius, serializer);
    sse_encode_list_prim_f_32_strict(self.matrix, serializer);
    sse_encode_list_svg_gradient_stop(self.stops, serializer);
    sse_encode_u_8(self.spread, serializer);
  }

  @protected
  void sse_encode_svg_gradient_stop(
    SvgGradientStop self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.offset, serializer);
    sse_encode_u_32(self.colorArgb, serializer);
  }

  @protected
  void sse_encode_svg_image(SvgImage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.x, serializer);
    sse_encode_f_32(self.y, serializer);
    sse_encode_f_32(self.width, serializer);
    sse_encode_f_32(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.data, serializer);
    sse_encode_svg_image_format(self.format, serializer);
  }

  @protected
  void sse_encode_svg_image_format(
    SvgImageFormat self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_svg_mask(SvgMask self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.kind, serializer);
    sse_encode_f_32(self.x, serializer);
    sse_encode_f_32(self.y, serializer);
    sse_encode_f_32(self.width, serializer);
    sse_encode_f_32(self.height, serializer);
    sse_encode_list_svg_path(self.paths, serializer);
  }

  @protected
  void sse_encode_svg_path(SvgPath self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.verbs, serializer);
    sse_encode_list_prim_f_32_strict(self.points, serializer);
    sse_encode_bool(self.hasFill, serializer);
    sse_encode_u_32(self.fillArgb, serializer);
    sse_encode_bool(self.evenOdd, serializer);
    sse_encode_bool(self.hasStroke, serializer);
    sse_encode_u_32(self.strokeArgb, serializer);
    sse_encode_f_32(self.strokeWidth, serializer);
    sse_encode_bool(self.strokeFirst, serializer);
    sse_encode_opt_box_autoadd_svg_gradient(self.fillGradient, serializer);
    sse_encode_opt_box_autoadd_svg_gradient(self.strokeGradient, serializer);
    sse_encode_opt_box_autoadd_svg_effects(self.effects, serializer);
  }

  @protected
  void sse_encode_svg_pattern(SvgPattern self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.x, serializer);
    sse_encode_f_32(self.y, serializer);
    sse_encode_f_32(self.width, serializer);
    sse_encode_f_32(self.height, serializer);
    sse_encode_list_prim_f_32_strict(self.matrix, serializer);
    sse_encode_list_svg_path(self.paths, serializer);
  }

  @protected
  void sse_encode_svg_scene(SvgScene self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.width, serializer);
    sse_encode_f_32(self.height, serializer);
    sse_encode_list_svg_path(self.paths, serializer);
    sse_encode_list_svg_image(self.images, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
