// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `append_clip_geometry`, `append_segments`, `append_subtree_paths`, `build_clips`, `build_gradient`, `build_mask`, `build_pattern`, `collect`, `concat`, `convert_gradient_stops`, `convert_image`, `convert_path`, `extend_inherited`, `gaussian_blur_of`, `inject_current_color`, `map`, `paint_argb`, `some_if_present`, `spread_to_u8`, `stop_rgb`, `system_fontdb`, `token_matrix`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Inherited`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

/// Parses [data] (SVG markup) into an [SvgScene]. Errors return a message.
///
/// [current_color] substitutes for the `currentColor` keyword in fill/stroke
/// paint values (0xAARRGGBB; alpha is ignored since SVG's `color` property
/// carries no alpha). `usvg::Options` (0.44) has no built-in hook for this
/// (`currentColor` resolves via `usvg`'s own `color`-attribute cascade,
/// defaulting to black), so when set, a `color="#RRGGBB"` attribute is
/// injected onto the root `<svg>` element before parsing — letting usvg's
/// existing cascade resolve it, while any explicit `color` already on the
/// root is left untouched.
///
/// 把 [data]（SVG 文本）解析为 [SvgScene]，出错返回错误信息。
///
/// [current_color] 用于替换 fill/stroke 中的 `currentColor` 关键字
/// （0xAARRGGBB；alpha 会被忽略，因为 SVG `color` 属性本身不带 alpha）。
/// `usvg::Options`（0.44）没有内置的注入钩子（`currentColor` 由 usvg 自身的
/// `color` 属性级联解析，缺省时回退黑色），所以设置该参数时会在解析前给根
/// `<svg>` 元素注入 `color="#RRGGBB"` 属性，借用 usvg 已有的级联机制解析；
/// 若根节点已显式声明 `color`，则保留不覆盖。
///
/// Example:
/// ```dart
/// final scene = parseSvg(data: '<svg .../>', currentColor: 0xFFFF7A00);
/// ```
SvgScene parseSvg({required String data, int? currentColor}) => RustLib
    .instance
    .api
    .crateApiSvgParseSvg(data: data, currentColor: currentColor);

/// Parses any CSS3/SVG colour string (`red`, `cornflowerblue`, `#RGB`,
/// `#RRGGBB`, `rgb()`, `rgba()`, `hsl()`, ...) into RGBA bytes, or returns
/// `None` when the string isn't a colour.
///
/// Exists so the Dart animation engine doesn't have to carry its own CSS
/// named-colour table: `svgtypes` (the crate usvg parses with) already has
/// the complete one. Called once per attribute at document-parse time, never
/// per animation frame.
///
/// 把任意 CSS3/SVG 颜色字符串（`red`、`cornflowerblue`、`#RGB`、`#RRGGBB`、
/// `rgb()`、`rgba()`、`hsl()` 等）解析为 RGBA 字节；不是颜色时返回 `None`。
///
/// 存在的意义是让 Dart 动画引擎不必自带一张 CSS 具名颜色表——`svgtypes`
/// （usvg 自身解析用的 crate）已经有完整的一张。只在文档解析阶段按属性调用
/// 一次，绝不在每一动画帧调用。
///
/// Example:
/// ```dart
/// final rgba = parseColor(s: 'cornflowerblue'); // [100, 149, 237, 255]
/// ```
///
/// Returns a 4-element `Vec<u8>` rather than `[u8; 4]` on purpose: FRB maps a
/// fixed-size array to its `U8Array4` wrapper, which drags
/// `package:collection` into the generated Dart and trips
/// `depend_on_referenced_packages` unless it's declared in `pubspec.yaml`.
/// A plain `Vec<u8>` maps to `Uint8List` with no new dependency.
///
/// 刻意返回 4 元素的 `Vec<u8>` 而非 `[u8; 4]`：FRB 会把定长数组映射成其
/// `U8Array4` 包装类型，从而给生成的 Dart 代码引入 `package:collection`，除非
/// 在 `pubspec.yaml` 里声明它，否则触发 `depend_on_referenced_packages` 告警。
/// 普通 `Vec<u8>` 映射为 `Uint8List`，不引入新依赖。
Uint8List? parseColor({required String s}) =>
    RustLib.instance.api.crateApiSvgParseColor(s: s);

/// Parses a full SVG `transform` list (`translate(10,20) rotate(45) scale(2)`,
/// `matrix(...)`, `skewX(...)`, ...) into the composed affine matrix
/// `[a, b, c, d, e, f]`, or `None` when the string is malformed.
///
/// Components compose left-to-right exactly as SVG specifies, and
/// `rotate(a cx cy)` is expanded to translate/rotate/translate by the
/// underlying grammar. Called once per `transform` attribute at
/// document-parse time, never per animation frame.
///
/// 把完整的 SVG `transform` 列表（`translate(10,20) rotate(45) scale(2)`、
/// `matrix(...)`、`skewX(...)` 等）解析为合成后的仿射矩阵 `[a, b, c, d, e, f]`；
/// 字符串非法时返回 `None`。
///
/// 各分量按 SVG 规范从左到右合成，`rotate(a cx cy)` 由底层语法自动展开为
/// translate/rotate/translate。只在文档解析阶段按 `transform` 属性调用一次，
/// 绝不在每一动画帧调用。
///
/// Example:
/// ```dart
/// final m = parseTransform(s: 'translate(10,20)'); // [1, 0, 0, 1, 10, 20]
/// ```
Float32List? parseTransform({required String s}) =>
    RustLib.instance.api.crateApiSvgParseTransform(s: s);

/// A resolved `feGaussianBlur`, in absolute-space sigma.
///
/// 已解析的 `feGaussianBlur`，sigma 已换算到绝对坐标空间。
class SvgBlur {
  /// Horizontal sigma. / 水平 sigma。
  final double stdDevX;

  /// Vertical sigma. / 垂直 sigma。
  final double stdDevY;

  const SvgBlur({required this.stdDevX, required this.stdDevY});

  @override
  int get hashCode => stdDevX.hashCode ^ stdDevY.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SvgBlur &&
          runtimeType == other.runtimeType &&
          stdDevX == other.stdDevX &&
          stdDevY == other.stdDevY;
}

/// One clip region: the union of a `<clipPath>`'s shapes, already mapped into
/// absolute space.
///
/// A path carrying several [SvgClip]s must be clipped by *all* of them (set
/// intersection) — that is how nested `clip-path` on a `<clipPath>` and
/// clip-paths inherited from several ancestor groups compose.
///
/// 单个裁剪区域：一个 `<clipPath>` 内各形状的并集，已映射到绝对坐标空间。
///
/// 一条路径若带多个 [SvgClip]，必须被**全部**裁剪（求交集）——`<clipPath>` 自身
/// 的嵌套 `clip-path`、以及从多层祖先分组继承来的 clip-path 就是这样合成的。
class SvgClip {
  /// Verbs, same encoding as [SvgPath.verbs]. / 动词，编码同 [SvgPath.verbs]。
  final Uint8List verbs;

  /// Flattened x,y pairs, same encoding as [SvgPath.points].
  /// 扁平 x,y 坐标对，编码同 [SvgPath.points]。
  final Float32List points;

  /// Even-odd fill rule for the clip region (else non-zero).
  /// 裁剪区域使用奇偶填充规则（否则非零环绕）。
  final bool evenOdd;

  const SvgClip({
    required this.verbs,
    required this.points,
    required this.evenOdd,
  });

  @override
  int get hashCode => verbs.hashCode ^ points.hashCode ^ evenOdd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SvgClip &&
          runtimeType == other.runtimeType &&
          verbs == other.verbs &&
          points == other.points &&
          evenOdd == other.evenOdd;
}

/// Bundles the clip/mask/blur/pattern fields that only apply to a minority of
/// paths (those under a `<clipPath>`/`<mask>`/blur `<filter>`, or painted
/// with a `<pattern>`). Grouped into one struct — rather than left as five
/// separate `Option`/`Vec` fields on [SvgPath] — so the overwhelmingly common
/// "no such feature" case serializes as a single `None` tag over FFI instead
/// of five independent empty/`None` tags.
///
/// 打包裁剪/遮罩/模糊/图案这几个只有少数路径用得到的字段（位于
/// `<clipPath>`/`<mask>`/模糊 `<filter>` 之下，或用 `<pattern>` 上色的路径）。
/// 归并成一个结构体——而不是在 [SvgPath] 上留 5 个独立的 `Option`/`Vec`
/// 字段——这样绝大多数"没有用到这些特效"的情况，跨 FFI 时只序列化一个
/// `None` tag，而不是 5 个各自独立的空/`None` tag。
class SvgEffects {
  /// Fill pattern, when the fill paint is a `<pattern>` (in which case
  /// [SvgPath::fill_argb] is only a grey fallback). / 填充图案，填充为
  /// `<pattern>` 时使用（此时 [SvgPath::fill_argb] 只是灰色兜底）。
  final SvgPattern? fillPattern;

  /// Stroke pattern, when the stroke paint is a `<pattern>`.
  /// 描边图案，描边为 `<pattern>` 时使用。
  final SvgPattern? strokePattern;

  /// Clip regions inherited from ancestor groups; the path must be clipped
  /// by all of them (intersection). Empty when unclipped.
  ///
  /// 从祖先分组继承来的裁剪区域；该路径必须被全部裁剪（求交集）。
  /// 无裁剪时为空。
  final List<SvgClip> clips;

  /// Mask inherited from the nearest ancestor group that declares one.
  /// 来自最近一个声明了遮罩的祖先分组的遮罩。
  final SvgMask? mask;

  /// Gaussian blur inherited from the nearest ancestor group whose `filter`
  /// is a single `feGaussianBlur`. / 来自最近一个 `filter` 为单个
  /// `feGaussianBlur` 的祖先分组的高斯模糊。
  final SvgBlur? blur;

  const SvgEffects({
    this.fillPattern,
    this.strokePattern,
    required this.clips,
    this.mask,
    this.blur,
  });

  @override
  int get hashCode =>
      fillPattern.hashCode ^
      strokePattern.hashCode ^
      clips.hashCode ^
      mask.hashCode ^
      blur.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SvgEffects &&
          runtimeType == other.runtimeType &&
          fillPattern == other.fillPattern &&
          strokePattern == other.strokePattern &&
          clips == other.clips &&
          mask == other.mask &&
          blur == other.blur;
}

/// A resolved linear/radial gradient paint.
///
/// Flattened into one struct (rather than an enum with per-variant fields) so
/// FRB can generate it as a plain Dart class without pulling in `freezed` —
/// see fsvg CLAUDE.md's dependency-management rule (new deps need sign-off);
/// `kind` is the discriminant, and the unused half of the linear/radial
/// fields is simply left at its default.
///
/// For `kind == 0` (linear): [x1]/[y1]/[x2]/[y2] are the endpoints, already
/// resolved into the same absolute coordinate space as [SvgPath.points]
/// (bbox-relative `objectBoundingBox` gradients and any `gradientTransform`
/// pre-baked in) — an affine map is fully determined by where it sends two
/// points, so no extra matrix is needed.
///
/// For `kind == 1` (radial): [x1]/[y1] is the focal point, [x2]/[y2] is the
/// center, [radius] is the radius — all three in the gradient's own local
/// space (not absolute), plus [matrix] (local → absolute,
/// `[a, b, c, d, e, f]` per SVG's `matrix(a,b,c,d,e,f)`) that the Dart side
/// must apply (e.g. via `ui.Gradient.radial`'s `matrix4`) — unlike linear, a
/// non-uniform bbox scale turns the circle into an ellipse, which two points
/// alone can't express.
///
/// 已解析的线性/径向渐变 paint。
///
/// 压平为一个结构体（而非带各变体字段的枚举），使 FRB 能生成普通 Dart 类而
/// 无需引入 `freezed`——见 fsvg CLAUDE.md 的依赖管理规则（新依赖需先征得同意）；
/// `kind` 是判别字段，线性/径向字段中用不到的那一半保持默认值即可。
///
/// `kind == 0`（线性）：[x1]/[y1]/[x2]/[y2] 是两个端点，已解析到与
/// [SvgPath.points] 相同的绝对坐标空间（bbox 相关的 `objectBoundingBox` 渐变
/// 及 `gradientTransform` 均已预烘焙）——仿射变换由其对两点的映射结果完全
/// 确定，无需额外矩阵。
///
/// `kind == 1`（径向）：[x1]/[y1] 是焦点，[x2]/[y2] 是圆心，[radius] 是半径——
/// 三者均在渐变自身的局部空间（非绝对空间），另加 [matrix]（局部→绝对，
/// `[a, b, c, d, e, f]`，对应 SVG `matrix(a,b,c,d,e,f)`）需由 Dart 侧应用
/// （例如通过 `ui.Gradient.radial` 的 `matrix4`）——与线性不同，非均匀 bbox
/// 缩放会把圆变成椭圆，仅凭两个点无法表达。
class SvgGradient {
  /// 0 = linear, 1 = radial. / 0 = 线性，1 = 径向。
  final int kind;

  /// Linear: start X. Radial: focal point X (local space).
  /// 线性：起点 X。径向：焦点 X（局部空间）。
  final double x1;

  /// Linear: start Y. Radial: focal point Y (local space).
  /// 线性：起点 Y。径向：焦点 Y（局部空间）。
  final double y1;

  /// Linear: end X. Radial: center X (local space).
  /// 线性：终点 X。径向：圆心 X（局部空间）。
  final double x2;

  /// Linear: end Y. Radial: center Y (local space).
  /// 线性：终点 Y。径向：圆心 Y（局部空间）。
  final double y2;

  /// Radial only: radius (local space); unused for linear.
  /// 仅径向：半径（局部空间）；线性时不使用。
  final double radius;

  /// Radial only: local-to-absolute affine `[a, b, c, d, e, f]`; empty for
  /// linear.
  /// 仅径向：局部到绝对空间的仿射变换 `[a, b, c, d, e, f]`；线性时为空。
  final Float32List matrix;

  /// Color stops, in offset order. / 色标，按 offset 顺序排列。
  final List<SvgGradientStop> stops;

  /// Spread mode: 0=pad, 1=reflect, 2=repeat. / 延展模式：0=pad，1=reflect，2=repeat。
  final int spread;

  const SvgGradient({
    required this.kind,
    required this.x1,
    required this.y1,
    required this.x2,
    required this.y2,
    required this.radius,
    required this.matrix,
    required this.stops,
    required this.spread,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      x1.hashCode ^
      y1.hashCode ^
      x2.hashCode ^
      y2.hashCode ^
      radius.hashCode ^
      matrix.hashCode ^
      stops.hashCode ^
      spread.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SvgGradient &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          x1 == other.x1 &&
          y1 == other.y1 &&
          x2 == other.x2 &&
          y2 == other.y2 &&
          radius == other.radius &&
          matrix == other.matrix &&
          stops == other.stops &&
          spread == other.spread;
}

/// One gradient color stop. / 单个渐变色标。
class SvgGradientStop {
  /// Position along the gradient in `[0, 1]`. / 沿渐变轴的位置，`[0, 1]`。
  final double offset;

  /// Stop color as 0xAARRGGBB (alpha already combines `stop-opacity` and the
  /// paint's own fill/stroke opacity). / 色标颜色 0xAARRGGBB（alpha 已合并
  /// `stop-opacity` 与该 paint 自身的填充/描边透明度）。
  final int colorArgb;

  const SvgGradientStop({required this.offset, required this.colorArgb});

  @override
  int get hashCode => offset.hashCode ^ colorArgb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SvgGradientStop &&
          runtimeType == other.runtimeType &&
          offset == other.offset &&
          colorArgb == other.colorArgb;
}

/// One embedded raster `<image>` node: absolute geometry + raw decoded bytes.
///
/// Only `usvg::ImageKind::Raster` (PNG/JPEG/GIF/WEBP) is represented here;
/// nested `<image>` referencing another SVG (`ImageKind::SVG`) is skipped
/// silently during collection — out of scope for this pass.
///
/// 单个内嵌位图 `<image>` 节点：绝对几何 + 原始解码字节。
///
/// 仅覆盖 `usvg::ImageKind::Raster`（PNG/JPEG/GIF/WEBP）；嵌套引用另一份 SVG 的
/// `<image>`（`ImageKind::SVG`）在收集阶段静默跳过——本轮不做。
class SvgImage {
  /// Absolute-space X. / 绝对坐标 X。
  final double x;

  /// Absolute-space Y. / 绝对坐标 Y。
  final double y;

  /// Absolute-space width. / 绝对坐标宽度。
  final double width;

  /// Absolute-space height. / 绝对坐标高度。
  final double height;

  /// Raw (still-encoded) image bytes, e.g. PNG file bytes.
  /// 原始（仍是编码态）图片字节，例如 PNG 文件字节。
  final Uint8List data;

  /// Encoding format of [data]. / [data] 的编码格式。
  final SvgImageFormat format;

  const SvgImage({
    required this.x,
    required this.y,
    required this.width,
    required this.height,
    required this.data,
    required this.format,
  });

  @override
  int get hashCode =>
      x.hashCode ^
      y.hashCode ^
      width.hashCode ^
      height.hashCode ^
      data.hashCode ^
      format.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SvgImage &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          width == other.width &&
          height == other.height &&
          data == other.data &&
          format == other.format;
}

/// Raster encodings usvg can hand back for `<image>`.
/// usvg 对 `<image>` 可返回的位图编码类型。
enum SvgImageFormat { png, jpeg, gif, webp }

/// A `<mask>` resolved into absolute-space content geometry plus its clipping
/// rect.
///
/// [paths] are the mask's own shapes (fully resolved paints included) — the
/// Dart side rasterizes them and uses either their luminance or their alpha
/// (per [kind]) as the coverage of the masked element.
///
/// 解析到绝对坐标空间的 `<mask>`：内容几何 + 遮罩矩形。
///
/// [paths] 是遮罩自身的形状（含已解析的 paint）——Dart 侧把它们光栅化，按
/// [kind] 取其亮度或 alpha 作为被遮罩元素的覆盖度。
class SvgMask {
  /// 0 = luminance (`mask-type="luminance"`, the default), 1 = alpha.
  /// 0 = 亮度（`mask-type="luminance"`，默认），1 = alpha。
  final int kind;

  /// Mask rect in absolute space: left. / 绝对空间遮罩矩形左边界。
  final double x;

  /// Mask rect in absolute space: top. / 绝对空间遮罩矩形上边界。
  final double y;

  /// Mask rect width. / 遮罩矩形宽。
  final double width;

  /// Mask rect height. / 遮罩矩形高。
  final double height;

  /// Mask content shapes, in absolute space. / 遮罩内容形状，绝对坐标空间。
  final List<SvgPath> paths;

  const SvgMask({
    required this.kind,
    required this.x,
    required this.y,
    required this.width,
    required this.height,
    required this.paths,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      x.hashCode ^
      y.hashCode ^
      width.hashCode ^
      height.hashCode ^
      paths.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SvgMask &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          x == other.x &&
          y == other.y &&
          width == other.width &&
          height == other.height &&
          paths == other.paths;
}

/// One path node: geometry (in absolute coords) plus fill/stroke.
///
/// 单个路径节点：几何（绝对坐标）+ 填充/描边。
class SvgPath {
  /// Verbs: 0=move 1=line 2=quad 3=cubic 4=close. / 动词：0 移动 1 直线 2 二次 3 三次 4 闭合。
  final Uint8List verbs;

  /// Flattened x,y coordinate pairs. / 扁平的 x,y 坐标对。
  final Float32List points;

  /// Whether a fill is present. / 是否有填充。
  final bool hasFill;

  /// Fill color as 0xAARRGGBB. / 填充色 0xAARRGGBB。
  final int fillArgb;

  /// Even-odd fill rule (else non-zero). / 奇偶填充规则（否则非零环绕）。
  final bool evenOdd;

  /// Whether a stroke is present. / 是否有描边。
  final bool hasStroke;

  /// Stroke color as 0xAARRGGBB. / 描边色 0xAARRGGBB。
  final int strokeArgb;

  /// Stroke width in px. / 描边宽度（px）。
  final double strokeWidth;

  /// Paint order: true paints stroke before fill (`paint-order="stroke fill"`),
  /// false (default) paints fill before stroke.
  ///
  /// 绘制顺序：true 表示先描边后填充（`paint-order="stroke fill"`），
  /// false（默认）表示先填充后描边。
  final bool strokeFirst;

  /// Fill gradient, when the fill paint is a linear/radial gradient (in
  /// which case [fill_argb] is unused). / 填充渐变，填充为渐变时使用（此时
  /// [fill_argb] 不生效）。
  final SvgGradient? fillGradient;

  /// Stroke gradient, when the stroke paint is a linear/radial gradient (in
  /// which case [stroke_argb] is unused). / 描边渐变，描边为渐变时使用
  /// （此时 [stroke_argb] 不生效）。
  final SvgGradient? strokeGradient;

  /// Clip/mask/blur/pattern extras, when this path uses any of them.
  /// `None` for the common case (no clipPath/mask/filter/pattern), which
  /// SSE serializes as a single tag instead of one tag per sub-field — see
  /// [SvgEffects].
  ///
  /// 裁剪/遮罩/模糊/图案等附加特效，任一被用到时才有值。多数路径都不用这些
  /// 特效（`None`），SSE 序列化时只写一个 tag，而不是像拆分成 5 个独立字段
  /// 那样每个都写一个 tag——详见 [SvgEffects]。
  final SvgEffects? effects;

  const SvgPath({
    required this.verbs,
    required this.points,
    required this.hasFill,
    required this.fillArgb,
    required this.evenOdd,
    required this.hasStroke,
    required this.strokeArgb,
    required this.strokeWidth,
    required this.strokeFirst,
    this.fillGradient,
    this.strokeGradient,
    this.effects,
  });

  @override
  int get hashCode =>
      verbs.hashCode ^
      points.hashCode ^
      hasFill.hashCode ^
      fillArgb.hashCode ^
      evenOdd.hashCode ^
      hasStroke.hashCode ^
      strokeArgb.hashCode ^
      strokeWidth.hashCode ^
      strokeFirst.hashCode ^
      fillGradient.hashCode ^
      strokeGradient.hashCode ^
      effects.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SvgPath &&
          runtimeType == other.runtimeType &&
          verbs == other.verbs &&
          points == other.points &&
          hasFill == other.hasFill &&
          fillArgb == other.fillArgb &&
          evenOdd == other.evenOdd &&
          hasStroke == other.hasStroke &&
          strokeArgb == other.strokeArgb &&
          strokeWidth == other.strokeWidth &&
          strokeFirst == other.strokeFirst &&
          fillGradient == other.fillGradient &&
          strokeGradient == other.strokeGradient &&
          effects == other.effects;
}

/// A `<pattern>` paint server resolved into a repeatable tile.
///
/// [paths] are the tile's contents in the pattern's own local space; [x]/[y]/
/// [width]/[height] is the tile rect in that same local space; [matrix]
/// (`[a, b, c, d, e, f]`) maps pattern-local space into the absolute space the
/// rest of the display list uses.
///
/// 已解析为可重复贴片的 `<pattern>` paint server。
///
/// [paths] 是贴片内容（图案自身局部空间）；[x]/[y]/[width]/[height] 是同一局部
/// 空间内的贴片矩形；[matrix]（`[a, b, c, d, e, f]`）把图案局部空间映射到显示
/// 列表其余部分所用的绝对空间。
class SvgPattern {
  /// Tile rect left, in pattern-local space. / 贴片矩形左边界（图案局部空间）。
  final double x;

  /// Tile rect top, in pattern-local space. / 贴片矩形上边界（图案局部空间）。
  final double y;

  /// Tile rect width. / 贴片矩形宽。
  final double width;

  /// Tile rect height. / 贴片矩形高。
  final double height;

  /// Pattern-local → absolute affine `[a, b, c, d, e, f]`.
  /// 图案局部 → 绝对空间的仿射矩阵 `[a, b, c, d, e, f]`。
  final Float32List matrix;

  /// Tile contents, in pattern-local space. / 贴片内容，图案局部空间。
  final List<SvgPath> paths;

  const SvgPattern({
    required this.x,
    required this.y,
    required this.width,
    required this.height,
    required this.matrix,
    required this.paths,
  });

  @override
  int get hashCode =>
      x.hashCode ^
      y.hashCode ^
      width.hashCode ^
      height.hashCode ^
      matrix.hashCode ^
      paths.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SvgPattern &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          width == other.width &&
          height == other.height &&
          matrix == other.matrix &&
          paths == other.paths;
}

/// A parsed SVG reduced to a flat list of paths with resolved paints.
///
/// 解析后的 SVG，规约为一组带已解析描边/填充的扁平路径。
class SvgScene {
  /// Intrinsic width in px. / 固有宽（px）。
  final double width;

  /// Intrinsic height in px. / 固有高（px）。
  final double height;

  /// Draw commands in paint order. / 按绘制顺序排列的绘制命令。
  final List<SvgPath> paths;

  /// Embedded raster images, in document order (drawn before [paths] — a
  /// simplifying z-order assumption, no interleaving with path draw order).
  ///
  /// 内嵌位图，按文档顺序排列（在 [paths] 之前绘制——简化的 z-order 假设，
  /// 不与路径绘制顺序交错）。
  final List<SvgImage> images;

  const SvgScene({
    required this.width,
    required this.height,
    required this.paths,
    required this.images,
  });

  @override
  int get hashCode =>
      width.hashCode ^ height.hashCode ^ paths.hashCode ^ images.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SvgScene &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          paths == other.paths &&
          images == other.images;
}
