import 'dart:async';
import 'dart:convert';

import 'package:flutter/foundation.dart';

/// Condition predicate; receives the manager's context map (see
/// [Layerman.setContext]). When provided it is the SOLE authority —
/// `route` / `requiresAuth` sugar is ignored (TS parity).
typedef OverlayPredicate = bool Function(Map<String, Object?> context);

/// Frequency-capping configuration. All present fields must pass (AND), and
/// counts increment when the overlay actually opens (TS parity).
///
/// * [session] — at most N times per manager instance (in memory).
/// * [total] — at most N times ever (persisted).
/// * [day]/[hour]/[minute] — at most N times per LOCAL calendar day/hour/minute
///   (persisted).
/// * [minGap] — a rolling minimum interval since the last open (persisted).
class OverlayCooldown {
  const OverlayCooldown({
    this.session,
    this.total,
    this.day,
    this.hour,
    this.minute,
    this.minGap,
  });

  final int? session;
  final int? total;
  final int? day;
  final int? hour;
  final int? minute;
  final Duration? minGap;

  bool get _needsPersistence =>
      total != null ||
      day != null ||
      hour != null ||
      minute != null ||
      minGap != null;
}

/// Pluggable persistence for [OverlayCooldown] counters. The default is
/// [MemoryCooldownStorage]; back it with `shared_preferences` (or anything
/// else) in real apps:
///
/// ```dart
/// class PrefsCooldownStorage implements OverlayCooldownStorage {
///   Future<String?> read(String key) async =>
///       (await SharedPreferences.getInstance()).getString(key);
///   Future<void> write(String key, String value) async =>
///       (await SharedPreferences.getInstance()).setString(key, value);
/// }
/// ```
abstract class OverlayCooldownStorage {
  Future<String?> read(String key);
  Future<void> write(String key, String value);
}

/// In-memory [OverlayCooldownStorage] (per-process; survives manager
/// re-creation when the same instance is shared).
class MemoryCooldownStorage implements OverlayCooldownStorage {
  final Map<String, String> _store = <String, String>{};

  @override
  Future<String?> read(String key) async => _store[key];

  @override
  Future<void> write(String key, String value) async => _store[key] = value;
}

/// A lightweight view of one managed entry, handed to [Layerman.clearWhere].
class OverlayRecord {
  const OverlayRecord._(this.id, this.slot, this.data, this.active, this.phase);

  final String id;
  final String slot;
  final Object? data;

  /// Whether the entry currently occupies a slot / overlaps (vs queued).
  final bool active;

  /// `pending` / `resolving` / `open` / `closing`.
  final String phase;
}

/// Context handed to a [Present] callback when the queue grants permission to
/// show an overlay.
class PresentContext {
  const PresentContext._(this.id, this.slot, this.data);

  /// Unique id of the queue entry (same as the id passed to / generated by
  /// [Layerman.open]).
  final String id;

  /// The serial slot this entry was queued in.
  final String slot;

  /// Opaque payload handed to [Layerman.open] (post-`resolve` if any).
  final Object? data;
}

/// Bidirectional handle returned by a [Present] callback.
///
/// Adapts a UI backend (showDialog / GetX / bot_toast / a self-managed
/// `OverlayEntry` / ...) to the orchestrator:
///
/// * [dismissed] — the backend's completion signal. It must complete when the
///   overlay is closed **through any path** (user tap, barrier, back button,
///   timeout, programmatic close). Its value becomes the result of
///   [Layerman.open].
/// * [dismiss] — lets the orchestrator close the backend (replace/preemption/
///   [Layerman.close]). Must target **this** overlay specifically (e.g.
///   pop by unique route name, `SnackbarController.close()`, `CancelFunc`) —
///   never "pop whatever is on top".
class PresentedOverlay<T> {
  PresentedOverlay({required this.dismissed, this.dismiss});

  /// Completes when the backend overlay is fully closed.
  final Future<T?> dismissed;

  /// Gracefully close the backend overlay, optionally delivering [result].
  /// When null the orchestrator cannot preempt this overlay; [Layerman.close]
  /// then only detaches it from the queue (the backend keeps its own lifecycle).
  final Future<void> Function([T? result])? dismiss;
}

/// Presents an overlay through a UI backend when the queue grants permission.
/// Called at most once per queue entry.
///
/// This is the SOLE rendering hook: the callback shows the UI however it likes
/// (it may push a route, call `Get.dialog`, fire `BotToast.show`, insert an
/// `OverlayEntry` the caller owns, ...) and returns a [PresentedOverlay] so the
/// orchestrator can await its close and preempt it. The manager itself never
/// touches the widget tree — it is UI-agnostic.
typedef Present<T> = PresentedOverlay<T> Function(PresentContext context);

enum _EntryPhase { pending, resolving, open, closing }

/// Internal, generic-erased queue/active record.
class _Entry {
  _Entry({
    required this.id,
    required this.slot,
    required this.priority,
    required this.seq,
    required this.overlap,
    required this.replace,
    required this.affix,
    required this.delay,
    required this.duration,
    required this.exitDuration,
    required this.when,
    required this.route,
    required this.requiresAuth,
    required this.dismissWhenUnmet,
    required this.cooldown,
    required this.beforeClose,
    required this.resolveData,
    required this.presentBackend,
    required this.settle,
    required this.getData,
    required this.setData,
  });

  final String id;
  final String slot;
  final int priority;
  int seq;
  final bool overlap;
  final bool replace;
  final bool affix;
  final Duration? delay;
  final Duration? duration;
  final Duration? exitDuration;

  final OverlayPredicate? when;
  final Object? route;
  final bool? requiresAuth;
  final bool dismissWhenUnmet;
  final OverlayCooldown? cooldown;
  final FutureOr<bool> Function()? beforeClose;

  /// Backend-driven data resolution (generic-erased); null skips the overlay.
  final Future<Object?> Function()? resolveData;

  /// Invokes the user's [Present] callback and wires the returned handle
  /// (generic-erased). Called once, when the queue grants this entry its slot.
  final void Function() presentBackend;

  /// Graceful backend close, wired by [presentBackend] once presented.
  Future<void> Function(Object? result)? externalDismiss;

  /// Whether the backend reported (or was told) it is fully closed.
  bool externalDone = false;

  /// Complete the result future exactly once (typed cast lives in the closure).
  final void Function(Object? result) settle;

  /// Live payload accessors (backing the mutable data seen by `resolve`,
  /// [Layerman.update] and the [PresentContext]).
  final Object? Function() getData;
  final void Function(Object? data) setData;

  _EntryPhase phase = _EntryPhase.pending;
  bool skipGap = false;
  bool delayConsumed = false;
  bool settled = false;
  bool paused = false;

  Timer? durationTimer;
  DateTime? durationDeadline;
  Duration? durationRemaining;
  Timer? removeTimer;

  bool get isActive =>
      phase == _EntryPhase.open ||
      phase == _EntryPhase.closing ||
      phase == _EntryPhase.resolving;

  bool get isShown =>
      phase == _EntryPhase.open || phase == _EntryPhase.closing;

  String get phaseName => switch (phase) {
        _EntryPhase.pending => 'pending',
        _EntryPhase.resolving => 'resolving',
        _EntryPhase.open => 'open',
        _EntryPhase.closing => 'closing',
      };
}

/// Per-slot serial state.
class _Slot {
  _Entry? active;
  final List<_Entry> queue = <_Entry>[];
  Timer? gapTimer;
  Timer? delayTimer;
  Timer? cooldownTimer;
  bool gapPending = false;
}

/// Persisted per-id cooldown counters.
class _CooldownRecord {
  _CooldownRecord({
    this.total = 0,
    this.dayBucket = '',
    this.dayCount = 0,
    this.hourBucket = '',
    this.hourCount = 0,
    this.minuteBucket = '',
    this.minuteCount = 0,
    this.lastShownMs,
  });

  factory _CooldownRecord.fromJson(Map<String, Object?> json) =>
      _CooldownRecord(
        total: (json['t'] as num?)?.toInt() ?? 0,
        dayBucket: json['db'] as String? ?? '',
        dayCount: (json['dc'] as num?)?.toInt() ?? 0,
        hourBucket: json['hb'] as String? ?? '',
        hourCount: (json['hc'] as num?)?.toInt() ?? 0,
        minuteBucket: json['mb'] as String? ?? '',
        minuteCount: (json['mc'] as num?)?.toInt() ?? 0,
        lastShownMs: (json['ls'] as num?)?.toInt(),
      );

  int total;
  String dayBucket;
  int dayCount;
  String hourBucket;
  int hourCount;
  String minuteBucket;
  int minuteCount;
  int? lastShownMs;

  Map<String, Object?> toJson() => <String, Object?>{
        't': total,
        'db': dayBucket,
        'dc': dayCount,
        'hb': hourBucket,
        'hc': hourCount,
        'mb': minuteBucket,
        'mc': minuteCount,
        'ls': lastShownMs,
      };
}

String _two(int n) => n < 10 ? '0$n' : '$n';
String _dayBucketOf(DateTime t) => '${t.year}-${_two(t.month)}-${_two(t.day)}';
String _hourBucketOf(DateTime t) => '${_dayBucketOf(t)}T${_two(t.hour)}';
String _minuteBucketOf(DateTime t) => '${_hourBucketOf(t)}:${_two(t.minute)}';

/// Hydrate-once cooldown store: reads run synchronously after [hydrate];
/// writes are fire-and-forget write-through.
class _CooldownStore {
  _CooldownStore(this._storage, this._key);

  final OverlayCooldownStorage _storage;
  final String _key;
  final Map<String, _CooldownRecord> _persisted = <String, _CooldownRecord>{};
  final Map<String, int> _session = <String, int>{};

  Future<void> hydrate() async {
    try {
      final raw = await _storage.read(_key);
      if (raw == null) return;
      final decoded = jsonDecode(raw) as Map<String, Object?>;
      decoded.forEach((id, value) {
        if (value is Map<String, Object?>) {
          _persisted[id] = _CooldownRecord.fromJson(value);
        } else if (value is Map) {
          _persisted[id] =
              _CooldownRecord.fromJson(value.cast<String, Object?>());
        }
      });
    } catch (_) {
      // Corrupt or unavailable storage degrades to empty counters.
    }
  }

  void _flush() {
    final json = <String, Object?>{
      for (final e in _persisted.entries) e.key: e.value.toJson(),
    };
    // Fire and forget; persistence failures must not break scheduling.
    // Called directly (not wrapped in Future()) so synchronous storages
    // commit immediately and no timer is left pending.
    try {
      unawaited(
        _storage.write(_key, jsonEncode(json)).catchError((Object _) {}),
      );
    } catch (_) {
      // Synchronous storage failure — ignore.
    }
  }

  // Equivalent to (and implemented via) `timeUntilEligible(...) ==
  // Duration.zero`: null (session/total block) and any positive wait both mean
  // "not yet", only an exact zero wait means every cap currently passes.
  bool canShow(String id, OverlayCooldown cd, DateTime now) =>
      timeUntilEligible(id, cd, now) == Duration.zero;

  /// How long until [id] could next pass [cd] on its **time-based** caps
  /// (`minGap` + day/hour/minute bucket rollover), or `null` if a cap that
  /// never auto-clears (`session`/`total`) currently blocks it. `Duration.zero`
  /// means the cooldown already passes (any remaining block is not time-based).
  /// Used to wake a queued entry exactly when its cooldown expires.
  Duration? timeUntilEligible(String id, OverlayCooldown cd, DateTime now) {
    if (cd.session != null && (_session[id] ?? 0) >= cd.session!) return null;
    final rec = _persisted[id];
    if (cd.total != null && (rec?.total ?? 0) >= cd.total!) return null;
    var wait = Duration.zero;
    void bump(Duration d) {
      if (d > wait) wait = d;
    }

    if (cd.day != null) {
      final c =
          rec != null && rec.dayBucket == _dayBucketOf(now) ? rec.dayCount : 0;
      if (c >= cd.day!) {
        final next = DateTime(now.year, now.month, now.day)
            .add(const Duration(days: 1));
        bump(next.difference(now));
      }
    }
    if (cd.hour != null) {
      final c = rec != null && rec.hourBucket == _hourBucketOf(now)
          ? rec.hourCount
          : 0;
      if (c >= cd.hour!) {
        final next = DateTime(now.year, now.month, now.day, now.hour)
            .add(const Duration(hours: 1));
        bump(next.difference(now));
      }
    }
    if (cd.minute != null) {
      final c = rec != null && rec.minuteBucket == _minuteBucketOf(now)
          ? rec.minuteCount
          : 0;
      if (c >= cd.minute!) {
        final next = DateTime(now.year, now.month, now.day, now.hour, now.minute)
            .add(const Duration(minutes: 1));
        bump(next.difference(now));
      }
    }
    if (cd.minGap != null && rec?.lastShownMs != null) {
      final remain = cd.minGap!.inMilliseconds -
          (now.millisecondsSinceEpoch - rec!.lastShownMs!);
      if (remain > 0) bump(Duration(milliseconds: remain));
    }
    return wait;
  }

  void record(String id, OverlayCooldown cd, DateTime now) {
    if (cd.session != null) _session[id] = (_session[id] ?? 0) + 1;
    if (!cd._needsPersistence) return;
    final rec = _persisted.putIfAbsent(id, _CooldownRecord.new);
    rec.total += 1;
    final dayB = _dayBucketOf(now);
    rec.dayCount = rec.dayBucket == dayB ? rec.dayCount + 1 : 1;
    rec.dayBucket = dayB;
    final hourB = _hourBucketOf(now);
    rec.hourCount = rec.hourBucket == hourB ? rec.hourCount + 1 : 1;
    rec.hourBucket = hourB;
    final minB = _minuteBucketOf(now);
    rec.minuteCount = rec.minuteBucket == minB ? rec.minuteCount + 1 : 1;
    rec.minuteBucket = minB;
    rec.lastShownMs = now.millisecondsSinceEpoch;
    _flush();
  }
}

/// A **headless** overlay **queue** orchestrator.
///
/// The manager owns scheduling, not rendering: it never inserts widgets or
/// touches the widget tree. Every overlay is shown through a [Present] backend
/// (showDialog / GetX / bot_toast / a self-managed `OverlayEntry` / ...) that
/// the manager invokes when the queue grants a slot, and closes through the
/// [PresentedOverlay] handle the backend returns. This keeps the core
/// UI-agnostic and mirrors the headless TS sister package. It provides:
///
/// * **serial one-at-a-time** queueing per named [slot] (default slot `''`),
///   with an optional [gap] between successive overlays;
/// * **priority** (higher shows first; FIFO within a priority);
/// * **replace** (preempt the current overlay of a slot), **affix** (protect
///   the current overlay from `replace`) and **overlap** (bypass the queue and
///   stack immediately);
/// * **conditions** (`when` / `route` / `requiresAuth` against [setContext],
///   with `dismissWhenUnmet` auto-dismissal) and **cooldown** frequency caps;
/// * backend-driven **`resolve`** data loading and a **`beforeClose`** guard;
/// * imperative **`Future<T?>` results** (like `showDialog`);
/// * **two-phase close** (a per-entry `exitDuration` grace + the backend's own
///   `dismissed` signal) so a backend can play its exit animation before the
///   queue advances;
/// * **pauseAll/resumeAll** full freeze and per-id **pause/resume** for
///   `duration` timers.
class Layerman extends ChangeNotifier {
  Layerman({
    this.gap = Duration.zero,
    OverlayCooldownStorage? cooldownStorage,
    String storageKey = 'layerman:cooldown',
    DateTime Function()? now,
    List<Object> pauseOnRoutes = const <Object>[],
  })  : assert(
          pauseOnRoutes.every(_isRoutePattern),
          'each pauseOnRoutes pattern must be a String, List<String> or RegExp',
        ),
        _pauseOnRoutes = pauseOnRoutes,
        _now = now ?? DateTime.now {
    _cooldowns =
        _CooldownStore(cooldownStorage ?? MemoryCooldownStorage(), storageKey);
    _ready = _cooldowns.hydrate();
  }

  /// Delay inserted between one overlay closing and the next one showing.
  final Duration gap;

  final DateTime Function() _now;
  late final _CooldownStore _cooldowns;
  late final Future<void> _ready;

  final Map<String, _Slot> _slots = <String, _Slot>{};
  final List<_Entry> _overlaps = <_Entry>[];
  final List<_Entry> _pendingOverlaps = <_Entry>[];
  final Map<String, _Entry> _byId = <String, _Entry>{};
  final Map<String, Object?> _context = <String, Object?>{};
  int _seqCounter = 0;
  final List<Object> _pauseOnRoutes;

  /// Explicit [pauseAll]/[resumeAll] state — independent of [_routeZonePaused];
  /// the effective [_paused] is their OR, so leaving a route zone doesn't
  /// override a still-active manual pause, and vice versa.
  bool _manualPaused = false;

  /// True while `_context['route']` matches one of [_pauseOnRoutes] — kept in
  /// sync by [_updateRouteZone], called from every [setContext].
  bool _routeZonePaused = false;

  bool get _paused => _manualPaused || _routeZonePaused;

  /// Completes when persisted cooldown counters have been hydrated. Await it
  /// before relying on `total`/`day`/... caps across restarts.
  Future<void> ready() => _ready;

  /// The `route` context key last set via [setContext] (`null` if never set).
  /// Typically kept in sync automatically by an `LayermanNavigatorObserver` —
  /// read this instead of maintaining a separate route mirror in the host.
  Object? get currentRoute => _context['route'];

  /// Whether the queue is currently frozen — via [pauseAll] or because the
  /// tracked route matches a `pauseOnRoutes` pattern.
  bool get isPaused => _paused;

  /// Ids currently waiting in any queue (observability/debugging).
  List<String> get queuedIds => <String>[
        for (final slot in _slots.values)
          for (final e in slot.queue) e.id,
        for (final e in _pendingOverlaps) e.id,
      ];

  /// Ids currently shown (open or closing), across serial slots and overlaps.
  List<String> get activeIds => <String>[
        for (final slot in _slots.values)
          if (slot.active != null && slot.active!.isShown) slot.active!.id,
        for (final e in _overlaps)
          if (e.isShown) e.id,
      ];

  /// Whether [id] is currently shown.
  bool isShowing(String id) {
    final e = _byId[id];
    return e != null && e.isShown;
  }

  /// Unhooks [e] from `slot.active` / `_overlaps` / `_pendingOverlaps`
  /// tracking. Returns whether it was occupying its slot's serial `active`
  /// position (callers that need to advance the queue check this).
  bool _detachFromActive(_Entry e) {
    final s = _slots[e.slot];
    final wasActive = s != null && s.active == e;
    if (wasActive) s.active = null;
    _overlaps.remove(e);
    _pendingOverlaps.remove(e);
    return wasActive;
  }

  /// Merge [partial] into the condition context and re-evaluate:
  /// * shown overlays whose conditions no longer pass are auto-dismissed
  ///   (unless they opted out via `dismissWhenUnmet: false`);
  /// * queued overlays that became eligible get a chance to show.
  ///
  /// Reserved keys used by the built-in sugar: `route` (String) and `auth`
  /// (bool). Everything else is free-form for `when` predicates.
  void setContext(Map<String, Object?> partial) {
    _context.addAll(partial);
    _updateRouteZone();
    final shown = <_Entry>[
      for (final s in _slots.values)
        if (s.active != null) s.active!,
      ..._overlaps,
    ];
    for (final e in shown) {
      if (e.isActive && e.dismissWhenUnmet && !_conditionsPass(e)) {
        _remove(e);
      }
    }
    for (final slot in _slots.keys.toList()) {
      _schedule(slot);
    }
    notifyListeners();
  }

  /// Re-check `_context['route']` against [_pauseOnRoutes] and flip
  /// [_routeZonePaused] on entry/exit — freezing/releasing exactly like a
  /// manual [pauseAll]/[resumeAll], but composed with it via [_paused]'s OR so
  /// leaving the zone doesn't undo an unrelated manual pause.
  void _updateRouteZone() {
    if (_pauseOnRoutes.isEmpty) return;
    final current = _context['route'];
    final matches = _pauseOnRoutes.any((p) => _routeMatches(p, current));
    if (matches == _routeZonePaused) return;
    final before = _paused;
    _routeZonePaused = matches;
    _applyPauseTransition(before);
  }

  /// Freeze everything: no new activation (serial, overlap, replace) and all
  /// running `duration` timers pause. Explicit [close]/[remove]/[clear] still
  /// work. [resumeAll] releases held overlaps and re-schedules.
  void pauseAll() {
    if (_manualPaused) return;
    final before = _paused;
    _manualPaused = true;
    _applyPauseTransition(before);
  }

  /// Undo [pauseAll]: release overlaps held while paused (if still eligible),
  /// thaw `duration` timers and re-schedule every slot.
  void resumeAll() {
    if (!_manualPaused) return;
    final before = _paused;
    _manualPaused = false;
    _applyPauseTransition(before);
  }

  /// Shared edge-trigger for the two independent pause sources
  /// ([_manualPaused] / [_routeZonePaused]): call `_applyFreeze`/`_applyRelease`
  /// only when the EFFECTIVE `_paused` actually crossed, so a source that
  /// flips while the other is already holding the queue paused (or open)
  /// doesn't double-freeze or release out from under it.
  void _applyPauseTransition(bool before) {
    final after = _paused;
    if (after == before) return;
    if (after) {
      _applyFreeze();
    } else {
      _applyRelease();
    }
  }

  void _applyFreeze() {
    for (final s in _slots.values) {
      _cancelCooldownTimer(s);
    }
    for (final e in _byId.values) {
      _freezeDuration(e);
    }
    notifyListeners();
  }

  void _applyRelease() {
    final held = List<_Entry>.of(_pendingOverlaps);
    _pendingOverlaps.clear();
    for (final e in held) {
      if (!_isCurrent(e)) continue;
      if (_eligible(e)) {
        _openOverlap(e);
      } else {
        _byId.remove(e.id);
        _finalize(e);
      }
    }
    for (final e in _byId.values) {
      _thawDuration(e);
    }
    for (final slot in _slots.keys.toList()) {
      _schedule(slot);
    }
    notifyListeners();
  }

  /// Freeze [id]'s `duration` countdown (the overlay stays shown).
  void pause(String id) {
    final e = _byId[id];
    if (e == null || e.paused) return;
    e.paused = true;
    _freezeDuration(e);
  }

  /// Resume [id]'s `duration` countdown with the remaining time.
  void resume(String id) {
    final e = _byId[id];
    if (e == null || !e.paused) return;
    e.paused = false;
    _thawDuration(e);
  }

  /// Merge [patch] into [id]'s `data` in place (map-into-map merges shallowly,
  /// anything else replaces) and notify listeners — without any queue change.
  ///
  /// The manager doesn't re-render (it owns no widgets); a backend that wants
  /// to reflect the new data should rebuild off this notification (or read
  /// `data` when it next builds).
  void update(String id, Object? patch) {
    final e = _byId[id];
    if (e == null) return;
    final current = e.getData();
    if (current is Map && patch is Map) {
      e.setData(<Object?, Object?>{...current, ...patch});
    } else {
      e.setData(patch);
    }
    notifyListeners();
  }

  /// Enqueue (or immediately show) an overlay, rendered through [present].
  ///
  /// Returns a [Future] that completes when the overlay closes: with the value
  /// the backend reported (via [PresentedOverlay.dismissed] or the `result`
  /// passed to [close]), or `null` when dismissed.
  ///
  /// [present] is the SOLE rendering hook (see [Present]/[PresentedOverlay]):
  /// invoked only when the queue grants this entry its slot, it shows the UI
  /// however it likes and returns a handle the manager awaits and can preempt.
  ///
  /// * [id] — unique key; if omitted an auto id is generated. Reusing an id
  ///   that is currently shown replaces it; reusing a queued id overrides it.
  /// * [slot] — independent serial queue (default `''`).
  /// * [priority] — higher shows first; ties break FIFO.
  /// * [delay] — wait before this overlay appears (overrides [gap] for itself).
  /// * [duration] — auto-close this long after opening.
  /// * [replace] — preempt the slot's current overlay, show immediately
  ///   (unless the current one is [affix]ed, or the replacer is not eligible).
  ///   The preempted overlay is closed (its result completes `null`); backends
  ///   cannot be faithfully re-presented, so there is no re-show.
  /// * [affix] — protect this overlay from `replace` (explicit [close]/
  ///   [remove]/[clear] still work; duplicate-id self-update is not blocked).
  /// * [overlap] — bypass the queue and stack on top immediately. Conditions/
  ///   cooldown act as a fire-gate: not eligible ⇒ dropped (result `null`).
  /// * [when]/[route]/[requiresAuth] — conditions against [setContext]
  ///   (`when` overrides the sugar); [dismissWhenUnmet] (default true)
  ///   auto-dismisses a shown overlay whose conditions stop holding.
  /// * [cooldown] — frequency caps; counts on real open.
  /// * [resolve] — backend-driven payload: called when the entry is granted
  ///   the slot; `null` skips the overlay, otherwise the value becomes `data`.
  /// * [beforeClose] — close guard: returning `false` cancels a [close].
  /// * [exitDuration] — extra grace between the backend's `dismissed` signal
  ///   and the queue advancing (lets a shared exit animation finish); null
  ///   advances immediately.
  Future<T?> open<T>({
    required Present<T> present,
    String? id,
    Object? data,
    String slot = '',
    int priority = 0,
    Duration? delay,
    Duration? duration,
    bool replace = false,
    bool affix = false,
    bool overlap = false,
    OverlayPredicate? when,
    Object? route,
    bool? requiresAuth,
    bool dismissWhenUnmet = true,
    OverlayCooldown? cooldown,
    Future<T?> Function()? resolve,
    FutureOr<bool> Function()? beforeClose,
    Duration? exitDuration,
  }) {
    assert(
      route == null || _isRoutePattern(route),
      'route must be a String, List<String> or RegExp',
    );
    final resolvedId = id ?? 'overlay:${++_seqCounter}';
    final completer = Completer<T?>();
    // Mutable payload backing `data`, the [PresentContext], `resolve`'s output
    // and [update]; lives here (not in a handle) so the whole thing stays
    // widget-free.
    var mutableData = data;

    late final _Entry entry;
    entry = _Entry(
      id: resolvedId,
      slot: slot,
      priority: priority,
      seq: ++_seqCounter,
      overlap: overlap,
      replace: replace,
      affix: affix,
      delay: delay,
      duration: duration,
      exitDuration: exitDuration,
      when: when,
      route: route,
      requiresAuth: requiresAuth,
      dismissWhenUnmet: dismissWhenUnmet,
      cooldown: cooldown,
      beforeClose: beforeClose,
      resolveData: resolve == null ? null : () async => await resolve(),
      settle: (Object? r) {
        if (!completer.isCompleted) completer.complete(r as T?);
      },
      getData: () => mutableData,
      setData: (v) => mutableData = v,
      presentBackend: () {
        final presented = present(
          PresentContext._(resolvedId, slot, mutableData),
        );
        final dismiss = presented.dismiss;
        entry.externalDismiss =
            dismiss == null ? null : (Object? r) => dismiss(r as T?);
        presented.dismissed.then(
          (T? r) => _onExternalDismissed(entry, r),
          onError: (Object _) => _onExternalDismissed(entry, null),
        );
      },
    );

    // Handle id reuse.
    final existing = _byId[resolvedId];
    if (existing != null) {
      if (existing.isActive) {
        _discardActive(existing); // replaced in place; old result -> null
        entry.skipGap = true;
      } else {
        _removeFromQueue(existing);
        _pendingOverlaps.remove(existing);
        _byId.remove(existing.id);
        _finalize(existing);
      }
    }
    _byId[resolvedId] = entry;

    if (overlap) {
      // Conditions/cooldown are a one-shot fire-gate for overlaps (TS rule:
      // "now or never") — but a paused manager holds them for resumeAll.
      if (!_eligible(entry)) {
        _byId.remove(entry.id);
        _finalize(entry);
      } else if (_paused) {
        _pendingOverlaps.add(entry);
      } else {
        _openOverlap(entry);
      }
      notifyListeners();
      return completer.future;
    }

    final s = _slotFor(slot);
    // A replace only preempts the current overlay when the replacer itself is
    // eligible right now (TS invariant 5b) and the manager is not paused; an
    // affixed current blocks preemption but the replacer keeps its front-band
    // ordering and shows next.
    if (replace && !_paused && _eligible(entry)) {
      entry.skipGap = true;
      final cur = s.active;
      if (cur != null && cur.isActive && !cur.affix) {
        // A backend that's been dismissed can't be faithfully re-presented
        // (that would re-run its side effects), so the preempted overlay is
        // discarded (closed + result `null`), never re-queued.
        _discardActive(cur);
      }
      // TS-parity: a replace arriving during the transition gap (or appear
      // delay) means "show me NOW" — skip the remaining gap / delay.
      if (s.gapPending) {
        s.gapTimer?.cancel();
        s.gapTimer = null;
        s.gapPending = false;
      }
      if (s.delayTimer != null) {
        s.delayTimer!.cancel();
        s.delayTimer = null;
      }
    }
    s.queue.add(entry);
    _schedule(slot);
    notifyListeners();
    return completer.future;
  }

  /// Two-phase close [id], optionally delivering [result]. A `beforeClose`
  /// guard returning `false` cancels the close.
  void close(String id, [Object? result]) {
    final e = _byId[id];
    if (e == null) return;
    _close(e, result);
  }

  /// Dismiss [id] (close with a `null` result).
  void dismiss(String id) => close(id);

  /// Immediately remove [id] with no exit grace (settles `null` if it had
  /// not been settled by a prior [close]). Bypasses `beforeClose`.
  void remove(String id) {
    final e = _byId[id];
    if (e == null) return;
    _remove(e);
  }

  /// Remove everything: queued and active, across all slots and overlaps.
  /// Unsettled results resolve `null`. Bypasses `beforeClose`.
  void clear() {
    for (final s in _slots.values) {
      _cancelCooldownTimer(s);
    }
    final all = _byId.values.toList();
    for (final e in all) {
      _remove(e, advance: false);
    }
    notifyListeners();
  }

  /// Selectively remove every entry (queued or shown) matching [test].
  /// "Close all of group X" is `clearWhere((r) => (r.data as MyData?)?.group == 'x')`.
  void clearWhere(bool Function(OverlayRecord record) test) {
    final selected = <_Entry>[
      for (final e in _byId.values.toList())
        if (test(OverlayRecord._(
          e.id,
          e.slot,
          e.getData(),
          e.isActive,
          e.phaseName,
        )))
          e,
    ];
    for (final e in selected) {
      _remove(e);
    }
  }

  // ── internals ──────────────────────────────────────────────────────────

  _Slot _slotFor(String slot) => _slots.putIfAbsent(slot, () => _Slot());

  void _removeFromQueue(_Entry e) {
    final s = _slots[e.slot];
    s?.queue.remove(e);
  }

  int _cmp(_Entry a, _Entry b) {
    // Replace entries form a front band: a preemptor must show before anything
    // that was already waiting (mirrors the TS package's replace-jumped rule),
    // e.g. when an affixed current blocked immediate preemption and the
    // replacer had to queue.
    if (a.replace != b.replace) return a.replace ? -1 : 1;
    if (a.priority != b.priority) return b.priority - a.priority;
    return a.seq - b.seq;
  }

  bool _eligible(_Entry e) => _conditionsPass(e) && _cooldownPass(e);

  bool _conditionsPass(_Entry e) {
    final when = e.when;
    if (when != null) return when(Map<String, Object?>.unmodifiable(_context));
    if (e.route != null && !_routeMatches(e.route!, _context['route'])) {
      return false;
    }
    if (e.requiresAuth != null && e.requiresAuth != (_context['auth'] == true)) {
      return false;
    }
    return true;
  }

  static bool _routeMatches(Object pattern, Object? current) {
    if (current is! String) return false;
    if (pattern is String) return pattern == current;
    if (pattern is List<String>) return pattern.contains(current);
    if (pattern is RegExp) return pattern.hasMatch(current);
    return false;
  }

  static bool _isRoutePattern(Object o) =>
      o is String || o is List<String> || o is RegExp;

  bool _cooldownPass(_Entry e) {
    final cd = e.cooldown;
    if (cd == null) return true;
    return _cooldowns.canShow(e.id, cd, _now());
  }

  void _cancelCooldownTimer(_Slot s) {
    s.cooldownTimer?.cancel();
    s.cooldownTimer = null;
  }

  void _schedule(String slot) {
    if (_paused) return;
    final s = _slotFor(slot);
    _cancelCooldownTimer(s);
    if (s.active != null) return; // slot occupied
    if (s.gapPending) return; // waiting out the transition gap
    if (s.delayTimer != null) return; // waiting out the per-overlay appear delay
    if (s.queue.isEmpty) return;

    final sorted = s.queue.toList()..sort(_cmp);
    _Entry? front;
    for (final e in sorted) {
      if (_eligible(e)) {
        front = e;
        break;
      }
    }
    if (front == null) {
      // Nothing eligible now. Entries blocked purely by a time-based cooldown
      // (minGap / bucket rollover) have a known expiry — wake the slot then so
      // they don't wait in the queue forever (cooldown expiry is otherwise not
      // a scheduling trigger).
      _armCooldownWake(slot, s);
      return; // ineligible entries WAIT
    }

    // Per-overlay appear delay.
    if (!front.skipGap &&
        !front.delayConsumed &&
        front.delay != null &&
        front.delay! > Duration.zero) {
      front.delayConsumed = true;
      s.delayTimer?.cancel();
      s.delayTimer = Timer(front.delay!, () {
        s.delayTimer = null;
        _schedule(slot);
      });
      return;
    }
    _activate(front);
  }

  /// Arm a one-shot timer to re-run [_schedule] when the soonest time-based
  /// cooldown among the slot's otherwise-eligible queued entries expires.
  void _armCooldownWake(String slot, _Slot s) {
    Duration? soonest;
    for (final e in s.queue) {
      final cd = e.cooldown;
      if (cd == null) continue;
      if (!_conditionsPass(e)) continue; // conditions are event-driven, not timed
      final w = _cooldowns.timeUntilEligible(e.id, cd, _now());
      if (w == null || w <= Duration.zero) continue;
      if (soonest == null || w < soonest) soonest = w;
    }
    if (soonest == null) return;
    // Small cushion so the timer fires strictly after the cap has cleared.
    s.cooldownTimer = Timer(soonest + const Duration(milliseconds: 16), () {
      s.cooldownTimer = null;
      _schedule(slot);
      notifyListeners();
    });
  }

  void _activate(_Entry e) {
    final s = _slotFor(e.slot);
    _removeFromQueue(e);
    s.active = e;
    final resolver = e.resolveData;
    if (resolver != null) {
      // Backend-driven payload: the slot is committed while resolving (not
      // interrupted by later arrivals); null ⇒ skip without opening.
      e.phase = _EntryPhase.resolving;
      notifyListeners();
      resolver().then(
        (data) => _onResolved(e, data),
        onError: (Object _) => _onResolved(e, null),
      );
      return;
    }
    _open(e);
  }

  void _onResolved(_Entry e, Object? data) {
    if (!_isCurrent(e) || e.phase != _EntryPhase.resolving) return;
    if (data == null) {
      // Backend said "don't show": skip without counting cooldown.
      final s = _slots[e.slot];
      if (s != null && s.active == e) s.active = null;
      _byId.remove(e.id);
      _finalize(e);
      notifyListeners();
      _schedule(e.slot);
      return;
    }
    e.setData(data);
    _open(e);
  }

  void _open(_Entry e) {
    e.phase = _EntryPhase.open;
    final cd = e.cooldown;
    if (cd != null) _cooldowns.record(e.id, cd, _now());
    e.presentBackend();
    _startDuration(e);
    notifyListeners();
  }

  void _openOverlap(_Entry e) {
    _overlaps.add(e);
    _open(e);
  }

  void _startDuration(_Entry e) {
    // A paused/frozen entry carries its REMAINING time (see [_freezeDuration]);
    // a fresh open uses the full `duration`.
    final d = e.durationRemaining ?? e.duration;
    if (d == null) {
      e.durationRemaining = null;
      return;
    }
    if (_paused || e.paused) {
      e.durationRemaining = d; // already d if this was a resume; harmless if so
      return;
    }
    e.durationRemaining = null;
    e.durationDeadline = _now().add(d);
    e.durationTimer = Timer(d, () => _close(e, null));
  }

  void _freezeDuration(_Entry e) {
    final timer = e.durationTimer;
    if (timer == null) return;
    timer.cancel();
    e.durationTimer = null;
    final deadline = e.durationDeadline;
    var remaining =
        deadline == null ? Duration.zero : deadline.difference(_now());
    if (remaining < Duration.zero) remaining = Duration.zero;
    e.durationRemaining = remaining;
  }

  void _thawDuration(_Entry e) {
    if (_paused || e.paused) return;
    final remaining = e.durationRemaining;
    if (remaining == null || e.phase != _EntryPhase.open) return;
    e.durationRemaining = null;
    e.durationDeadline = _now().add(remaining);
    e.durationTimer = Timer(remaining, () => _close(e, null));
  }

  /// Whether [e] is still the live, tracked entry for its id — false once it's
  /// been removed/replaced-in-place (a stale async callback from an entry no
  /// longer in `_byId` must not act on it).
  bool _isCurrent(_Entry e) => _byId[e.id] == e;

  /// Whether [e] can still be meaningfully closed (actually shown).
  bool _closable(_Entry e) => e.phase == _EntryPhase.open;

  void _close(_Entry e, Object? result) {
    if (!_closable(e)) return;

    final guard = e.beforeClose;
    if (guard == null) {
      _doClose(e, result);
      return;
    }
    final FutureOr<bool> verdict;
    try {
      verdict = guard();
    } catch (_) {
      return; // a throwing guard cancels the close
    }
    if (verdict is bool) {
      if (verdict) _doClose(e, result);
      return;
    }
    verdict.then(
      (ok) {
        // Re-check current state at resolution time — the entry may have been
        // removed/replaced while the guard was pending.
        if (ok && _isCurrent(e) && _closable(e)) _doClose(e, result);
      },
      onError: (Object _) {
        // A failing guard cancels the close.
      },
    );
  }

  void _doClose(_Entry e, Object? result) {
    e.durationTimer?.cancel();
    e.durationTimer = null;
    e.durationRemaining = null;
    _settle(e, result);
    e.phase = _EntryPhase.closing;
    notifyListeners();
    final dismiss = e.externalDismiss;
    if (dismiss == null || e.externalDone) {
      // Backend already closed, or cannot be closed by us: just detach.
      _remove(e);
    } else {
      // Graceful backend close; its dismissed signal drives removal
      // (plus the optional exitDuration grace) in _onExternalDismissed.
      dismiss(result);
    }
  }

  /// The backend reported it is fully closed (user tap, barrier, back button,
  /// timeout, or our own dismiss). Settle and advance the queue.
  void _onExternalDismissed(_Entry e, Object? result) {
    e.externalDone = true;
    _settle(e, result);
    if (!_isCurrent(e)) return; // already removed / replaced in place
    if (e.phase == _EntryPhase.open) {
      // Closed directly by the backend (not via our close()).
      e.phase = _EntryPhase.closing;
      notifyListeners();
    }
    final grace = e.exitDuration;
    if (grace != null && grace > Duration.zero) {
      e.removeTimer?.cancel();
      e.removeTimer = Timer(grace, () => _remove(e));
    } else {
      _remove(e);
    }
  }

  /// Remove an active/queued entry from the world. When [advance] is true and
  /// it occupied a serial slot, the queue is advanced (after [gap]).
  void _remove(_Entry e, {bool advance = true}) {
    e.durationTimer?.cancel();
    e.removeTimer?.cancel();
    e.durationTimer = null;
    e.removeTimer = null;

    _byId.remove(e.id);
    _dismissBackendBestEffort(e);

    final wasSerialActive = _detachFromActive(e);
    _removeFromQueue(e);

    _finalize(e);

    if (advance && wasSerialActive) {
      final s = _slotFor(e.slot);
      if (gap > Duration.zero) {
        s.gapPending = true;
        s.gapTimer?.cancel();
        s.gapTimer = Timer(gap, () {
          s.gapPending = false;
          s.gapTimer = null;
          _schedule(e.slot);
          notifyListeners();
        });
      } else {
        _schedule(e.slot);
      }
    }
    notifyListeners();
  }

  // Deliberately NOT `_remove(e, advance: false)`: that also calls
  // `notifyListeners()`, which would fire mid-`open()` with transient state
  // (this entry gone, the new one not yet enqueued) — the caller's own
  // trailing `notifyListeners()` is the only one that should fire here.
  void _discardActive(_Entry e) {
    e.durationTimer?.cancel();
    e.removeTimer?.cancel();
    _byId.remove(e.id);
    _dismissBackendBestEffort(e);
    _detachFromActive(e);
    _finalize(e);
  }

  /// When an entry leaves the queue while its backend may still be showing
  /// (replace/clear/remove), ask the backend to close, fire-and-forget.
  void _dismissBackendBestEffort(_Entry e) {
    if (e.externalDone) return;
    e.externalDone = true; // its dismissed signal must not re-drive removal
    e.externalDismiss?.call(null);
  }

  void _finalize(_Entry e) {
    _settle(e, null);
  }

  void _settle(_Entry e, Object? result) {
    if (e.settled) return;
    e.settled = true;
    e.settle(result);
  }

  @override
  void dispose() {
    for (final s in _slots.values) {
      s.gapTimer?.cancel();
      s.delayTimer?.cancel();
      s.cooldownTimer?.cancel();
    }
    clear();
    _disposed = true;
    super.dispose();
  }

  bool _disposed = false;

  /// Whether [dispose] has been called. Lets a deferred callback (e.g.
  /// `LayermanNavigatorObserver`'s post-frame `setContext`) check it's not
  /// about to call into a manager that was torn down in the meantime.
  bool get isDisposed => _disposed;
}
