// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -705259901;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__simple__greet_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "greet",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_name = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::simple::greet(api_name))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::simple::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__svg__parse_color_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "parse_color",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_s = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::svg::parse_color(api_s))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__svg__parse_svg_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "parse_svg",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_data = <String>::sse_decode(&mut deserializer);
            let api_current_color = <Option<u32>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api::svg::parse_svg(api_data, api_current_color)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__svg__parse_transform_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "parse_transform",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_s = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::svg::parse_transform(api_s))?;
                Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<f32>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::svg::SvgClip> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::svg::SvgClip>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::svg::SvgGradientStop> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::svg::SvgGradientStop>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::svg::SvgImage> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::svg::SvgImage>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::svg::SvgPath> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::svg::SvgPath>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<crate::api::svg::SvgBlur> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::svg::SvgBlur>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::svg::SvgEffects> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::svg::SvgEffects>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::svg::SvgGradient> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::svg::SvgGradient>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::svg::SvgMask> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::svg::SvgMask>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::svg::SvgPattern> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::svg::SvgPattern>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<Vec<f32>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<Vec<f32>>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<Vec<u8>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<Vec<u8>>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::svg::SvgBlur {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_stdDevX = <f32>::sse_decode(deserializer);
        let mut var_stdDevY = <f32>::sse_decode(deserializer);
        return crate::api::svg::SvgBlur {
            std_dev_x: var_stdDevX,
            std_dev_y: var_stdDevY,
        };
    }
}

impl SseDecode for crate::api::svg::SvgClip {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_verbs = <Vec<u8>>::sse_decode(deserializer);
        let mut var_points = <Vec<f32>>::sse_decode(deserializer);
        let mut var_evenOdd = <bool>::sse_decode(deserializer);
        return crate::api::svg::SvgClip {
            verbs: var_verbs,
            points: var_points,
            even_odd: var_evenOdd,
        };
    }
}

impl SseDecode for crate::api::svg::SvgEffects {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_fillPattern = <Option<crate::api::svg::SvgPattern>>::sse_decode(deserializer);
        let mut var_strokePattern = <Option<crate::api::svg::SvgPattern>>::sse_decode(deserializer);
        let mut var_clips = <Vec<crate::api::svg::SvgClip>>::sse_decode(deserializer);
        let mut var_mask = <Option<crate::api::svg::SvgMask>>::sse_decode(deserializer);
        let mut var_blur = <Option<crate::api::svg::SvgBlur>>::sse_decode(deserializer);
        return crate::api::svg::SvgEffects {
            fill_pattern: var_fillPattern,
            stroke_pattern: var_strokePattern,
            clips: var_clips,
            mask: var_mask,
            blur: var_blur,
        };
    }
}

impl SseDecode for crate::api::svg::SvgGradient {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <u8>::sse_decode(deserializer);
        let mut var_x1 = <f32>::sse_decode(deserializer);
        let mut var_y1 = <f32>::sse_decode(deserializer);
        let mut var_x2 = <f32>::sse_decode(deserializer);
        let mut var_y2 = <f32>::sse_decode(deserializer);
        let mut var_radius = <f32>::sse_decode(deserializer);
        let mut var_matrix = <Vec<f32>>::sse_decode(deserializer);
        let mut var_stops = <Vec<crate::api::svg::SvgGradientStop>>::sse_decode(deserializer);
        let mut var_spread = <u8>::sse_decode(deserializer);
        return crate::api::svg::SvgGradient {
            kind: var_kind,
            x1: var_x1,
            y1: var_y1,
            x2: var_x2,
            y2: var_y2,
            radius: var_radius,
            matrix: var_matrix,
            stops: var_stops,
            spread: var_spread,
        };
    }
}

impl SseDecode for crate::api::svg::SvgGradientStop {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_offset = <f32>::sse_decode(deserializer);
        let mut var_colorArgb = <u32>::sse_decode(deserializer);
        return crate::api::svg::SvgGradientStop {
            offset: var_offset,
            color_argb: var_colorArgb,
        };
    }
}

impl SseDecode for crate::api::svg::SvgImage {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_x = <f32>::sse_decode(deserializer);
        let mut var_y = <f32>::sse_decode(deserializer);
        let mut var_width = <f32>::sse_decode(deserializer);
        let mut var_height = <f32>::sse_decode(deserializer);
        let mut var_matrix = <Vec<f32>>::sse_decode(deserializer);
        let mut var_data = <Vec<u8>>::sse_decode(deserializer);
        let mut var_format = <crate::api::svg::SvgImageFormat>::sse_decode(deserializer);
        let mut var_clips = <Vec<crate::api::svg::SvgClip>>::sse_decode(deserializer);
        let mut var_mask = <Option<crate::api::svg::SvgMask>>::sse_decode(deserializer);
        let mut var_blur = <Option<crate::api::svg::SvgBlur>>::sse_decode(deserializer);
        return crate::api::svg::SvgImage {
            x: var_x,
            y: var_y,
            width: var_width,
            height: var_height,
            matrix: var_matrix,
            data: var_data,
            format: var_format,
            clips: var_clips,
            mask: var_mask,
            blur: var_blur,
        };
    }
}

impl SseDecode for crate::api::svg::SvgImageFormat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::svg::SvgImageFormat::Png,
            1 => crate::api::svg::SvgImageFormat::Jpeg,
            2 => crate::api::svg::SvgImageFormat::Gif,
            3 => crate::api::svg::SvgImageFormat::Webp,
            _ => unreachable!("Invalid variant for SvgImageFormat: {}", inner),
        };
    }
}

impl SseDecode for crate::api::svg::SvgMask {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <u8>::sse_decode(deserializer);
        let mut var_x = <f32>::sse_decode(deserializer);
        let mut var_y = <f32>::sse_decode(deserializer);
        let mut var_width = <f32>::sse_decode(deserializer);
        let mut var_height = <f32>::sse_decode(deserializer);
        let mut var_paths = <Vec<crate::api::svg::SvgPath>>::sse_decode(deserializer);
        return crate::api::svg::SvgMask {
            kind: var_kind,
            x: var_x,
            y: var_y,
            width: var_width,
            height: var_height,
            paths: var_paths,
        };
    }
}

impl SseDecode for crate::api::svg::SvgPath {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_verbs = <Vec<u8>>::sse_decode(deserializer);
        let mut var_points = <Vec<f32>>::sse_decode(deserializer);
        let mut var_hasFill = <bool>::sse_decode(deserializer);
        let mut var_fillArgb = <u32>::sse_decode(deserializer);
        let mut var_evenOdd = <bool>::sse_decode(deserializer);
        let mut var_hasStroke = <bool>::sse_decode(deserializer);
        let mut var_strokeArgb = <u32>::sse_decode(deserializer);
        let mut var_strokeWidth = <f32>::sse_decode(deserializer);
        let mut var_strokeFirst = <bool>::sse_decode(deserializer);
        let mut var_fillGradient = <Option<crate::api::svg::SvgGradient>>::sse_decode(deserializer);
        let mut var_strokeGradient =
            <Option<crate::api::svg::SvgGradient>>::sse_decode(deserializer);
        let mut var_effects = <Option<crate::api::svg::SvgEffects>>::sse_decode(deserializer);
        return crate::api::svg::SvgPath {
            verbs: var_verbs,
            points: var_points,
            has_fill: var_hasFill,
            fill_argb: var_fillArgb,
            even_odd: var_evenOdd,
            has_stroke: var_hasStroke,
            stroke_argb: var_strokeArgb,
            stroke_width: var_strokeWidth,
            stroke_first: var_strokeFirst,
            fill_gradient: var_fillGradient,
            stroke_gradient: var_strokeGradient,
            effects: var_effects,
        };
    }
}

impl SseDecode for crate::api::svg::SvgPattern {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_x = <f32>::sse_decode(deserializer);
        let mut var_y = <f32>::sse_decode(deserializer);
        let mut var_width = <f32>::sse_decode(deserializer);
        let mut var_height = <f32>::sse_decode(deserializer);
        let mut var_matrix = <Vec<f32>>::sse_decode(deserializer);
        let mut var_paths = <Vec<crate::api::svg::SvgPath>>::sse_decode(deserializer);
        return crate::api::svg::SvgPattern {
            x: var_x,
            y: var_y,
            width: var_width,
            height: var_height,
            matrix: var_matrix,
            paths: var_paths,
        };
    }
}

impl SseDecode for crate::api::svg::SvgScene {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_width = <f32>::sse_decode(deserializer);
        let mut var_height = <f32>::sse_decode(deserializer);
        let mut var_paths = <Vec<crate::api::svg::SvgPath>>::sse_decode(deserializer);
        let mut var_images = <Vec<crate::api::svg::SvgImage>>::sse_decode(deserializer);
        return crate::api::svg::SvgScene {
            width: var_width,
            height: var_height,
            paths: var_paths,
            images: var_images,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        2 => wire__crate__api__simple__init_app_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__simple__greet_impl(ptr, rust_vec_len, data_len),
        3 => wire__crate__api__svg__parse_color_impl(ptr, rust_vec_len, data_len),
        4 => wire__crate__api__svg__parse_svg_impl(ptr, rust_vec_len, data_len),
        5 => wire__crate__api__svg__parse_transform_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::svg::SvgBlur {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.std_dev_x.into_into_dart().into_dart(),
            self.std_dev_y.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::svg::SvgBlur {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::svg::SvgBlur> for crate::api::svg::SvgBlur {
    fn into_into_dart(self) -> crate::api::svg::SvgBlur {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::svg::SvgClip {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.verbs.into_into_dart().into_dart(),
            self.points.into_into_dart().into_dart(),
            self.even_odd.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::svg::SvgClip {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::svg::SvgClip> for crate::api::svg::SvgClip {
    fn into_into_dart(self) -> crate::api::svg::SvgClip {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::svg::SvgEffects {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.fill_pattern.into_into_dart().into_dart(),
            self.stroke_pattern.into_into_dart().into_dart(),
            self.clips.into_into_dart().into_dart(),
            self.mask.into_into_dart().into_dart(),
            self.blur.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::svg::SvgEffects {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::svg::SvgEffects>
    for crate::api::svg::SvgEffects
{
    fn into_into_dart(self) -> crate::api::svg::SvgEffects {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::svg::SvgGradient {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.x1.into_into_dart().into_dart(),
            self.y1.into_into_dart().into_dart(),
            self.x2.into_into_dart().into_dart(),
            self.y2.into_into_dart().into_dart(),
            self.radius.into_into_dart().into_dart(),
            self.matrix.into_into_dart().into_dart(),
            self.stops.into_into_dart().into_dart(),
            self.spread.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::svg::SvgGradient {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::svg::SvgGradient>
    for crate::api::svg::SvgGradient
{
    fn into_into_dart(self) -> crate::api::svg::SvgGradient {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::svg::SvgGradientStop {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.offset.into_into_dart().into_dart(),
            self.color_argb.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::svg::SvgGradientStop
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::svg::SvgGradientStop>
    for crate::api::svg::SvgGradientStop
{
    fn into_into_dart(self) -> crate::api::svg::SvgGradientStop {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::svg::SvgImage {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.x.into_into_dart().into_dart(),
            self.y.into_into_dart().into_dart(),
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
            self.matrix.into_into_dart().into_dart(),
            self.data.into_into_dart().into_dart(),
            self.format.into_into_dart().into_dart(),
            self.clips.into_into_dart().into_dart(),
            self.mask.into_into_dart().into_dart(),
            self.blur.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::svg::SvgImage {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::svg::SvgImage> for crate::api::svg::SvgImage {
    fn into_into_dart(self) -> crate::api::svg::SvgImage {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::svg::SvgImageFormat {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Png => 0.into_dart(),
            Self::Jpeg => 1.into_dart(),
            Self::Gif => 2.into_dart(),
            Self::Webp => 3.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::svg::SvgImageFormat
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::svg::SvgImageFormat>
    for crate::api::svg::SvgImageFormat
{
    fn into_into_dart(self) -> crate::api::svg::SvgImageFormat {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::svg::SvgMask {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.x.into_into_dart().into_dart(),
            self.y.into_into_dart().into_dart(),
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
            self.paths.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::svg::SvgMask {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::svg::SvgMask> for crate::api::svg::SvgMask {
    fn into_into_dart(self) -> crate::api::svg::SvgMask {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::svg::SvgPath {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.verbs.into_into_dart().into_dart(),
            self.points.into_into_dart().into_dart(),
            self.has_fill.into_into_dart().into_dart(),
            self.fill_argb.into_into_dart().into_dart(),
            self.even_odd.into_into_dart().into_dart(),
            self.has_stroke.into_into_dart().into_dart(),
            self.stroke_argb.into_into_dart().into_dart(),
            self.stroke_width.into_into_dart().into_dart(),
            self.stroke_first.into_into_dart().into_dart(),
            self.fill_gradient.into_into_dart().into_dart(),
            self.stroke_gradient.into_into_dart().into_dart(),
            self.effects.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::svg::SvgPath {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::svg::SvgPath> for crate::api::svg::SvgPath {
    fn into_into_dart(self) -> crate::api::svg::SvgPath {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::svg::SvgPattern {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.x.into_into_dart().into_dart(),
            self.y.into_into_dart().into_dart(),
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
            self.matrix.into_into_dart().into_dart(),
            self.paths.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::svg::SvgPattern {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::svg::SvgPattern>
    for crate::api::svg::SvgPattern
{
    fn into_into_dart(self) -> crate::api::svg::SvgPattern {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::svg::SvgScene {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
            self.paths.into_into_dart().into_dart(),
            self.images.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::svg::SvgScene {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::svg::SvgScene> for crate::api::svg::SvgScene {
    fn into_into_dart(self) -> crate::api::svg::SvgScene {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <f32>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::svg::SvgClip> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::svg::SvgClip>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::svg::SvgGradientStop> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::svg::SvgGradientStop>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::svg::SvgImage> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::svg::SvgImage>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::svg::SvgPath> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::svg::SvgPath>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::svg::SvgBlur> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::svg::SvgBlur>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::svg::SvgEffects> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::svg::SvgEffects>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::svg::SvgGradient> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::svg::SvgGradient>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::svg::SvgMask> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::svg::SvgMask>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::svg::SvgPattern> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::svg::SvgPattern>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<Vec<f32>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <Vec<f32>>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<Vec<u8>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <Vec<u8>>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::svg::SvgBlur {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f32>::sse_encode(self.std_dev_x, serializer);
        <f32>::sse_encode(self.std_dev_y, serializer);
    }
}

impl SseEncode for crate::api::svg::SvgClip {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.verbs, serializer);
        <Vec<f32>>::sse_encode(self.points, serializer);
        <bool>::sse_encode(self.even_odd, serializer);
    }
}

impl SseEncode for crate::api::svg::SvgEffects {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<crate::api::svg::SvgPattern>>::sse_encode(self.fill_pattern, serializer);
        <Option<crate::api::svg::SvgPattern>>::sse_encode(self.stroke_pattern, serializer);
        <Vec<crate::api::svg::SvgClip>>::sse_encode(self.clips, serializer);
        <Option<crate::api::svg::SvgMask>>::sse_encode(self.mask, serializer);
        <Option<crate::api::svg::SvgBlur>>::sse_encode(self.blur, serializer);
    }
}

impl SseEncode for crate::api::svg::SvgGradient {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u8>::sse_encode(self.kind, serializer);
        <f32>::sse_encode(self.x1, serializer);
        <f32>::sse_encode(self.y1, serializer);
        <f32>::sse_encode(self.x2, serializer);
        <f32>::sse_encode(self.y2, serializer);
        <f32>::sse_encode(self.radius, serializer);
        <Vec<f32>>::sse_encode(self.matrix, serializer);
        <Vec<crate::api::svg::SvgGradientStop>>::sse_encode(self.stops, serializer);
        <u8>::sse_encode(self.spread, serializer);
    }
}

impl SseEncode for crate::api::svg::SvgGradientStop {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f32>::sse_encode(self.offset, serializer);
        <u32>::sse_encode(self.color_argb, serializer);
    }
}

impl SseEncode for crate::api::svg::SvgImage {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f32>::sse_encode(self.x, serializer);
        <f32>::sse_encode(self.y, serializer);
        <f32>::sse_encode(self.width, serializer);
        <f32>::sse_encode(self.height, serializer);
        <Vec<f32>>::sse_encode(self.matrix, serializer);
        <Vec<u8>>::sse_encode(self.data, serializer);
        <crate::api::svg::SvgImageFormat>::sse_encode(self.format, serializer);
        <Vec<crate::api::svg::SvgClip>>::sse_encode(self.clips, serializer);
        <Option<crate::api::svg::SvgMask>>::sse_encode(self.mask, serializer);
        <Option<crate::api::svg::SvgBlur>>::sse_encode(self.blur, serializer);
    }
}

impl SseEncode for crate::api::svg::SvgImageFormat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::svg::SvgImageFormat::Png => 0,
                crate::api::svg::SvgImageFormat::Jpeg => 1,
                crate::api::svg::SvgImageFormat::Gif => 2,
                crate::api::svg::SvgImageFormat::Webp => 3,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::svg::SvgMask {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u8>::sse_encode(self.kind, serializer);
        <f32>::sse_encode(self.x, serializer);
        <f32>::sse_encode(self.y, serializer);
        <f32>::sse_encode(self.width, serializer);
        <f32>::sse_encode(self.height, serializer);
        <Vec<crate::api::svg::SvgPath>>::sse_encode(self.paths, serializer);
    }
}

impl SseEncode for crate::api::svg::SvgPath {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.verbs, serializer);
        <Vec<f32>>::sse_encode(self.points, serializer);
        <bool>::sse_encode(self.has_fill, serializer);
        <u32>::sse_encode(self.fill_argb, serializer);
        <bool>::sse_encode(self.even_odd, serializer);
        <bool>::sse_encode(self.has_stroke, serializer);
        <u32>::sse_encode(self.stroke_argb, serializer);
        <f32>::sse_encode(self.stroke_width, serializer);
        <bool>::sse_encode(self.stroke_first, serializer);
        <Option<crate::api::svg::SvgGradient>>::sse_encode(self.fill_gradient, serializer);
        <Option<crate::api::svg::SvgGradient>>::sse_encode(self.stroke_gradient, serializer);
        <Option<crate::api::svg::SvgEffects>>::sse_encode(self.effects, serializer);
    }
}

impl SseEncode for crate::api::svg::SvgPattern {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f32>::sse_encode(self.x, serializer);
        <f32>::sse_encode(self.y, serializer);
        <f32>::sse_encode(self.width, serializer);
        <f32>::sse_encode(self.height, serializer);
        <Vec<f32>>::sse_encode(self.matrix, serializer);
        <Vec<crate::api::svg::SvgPath>>::sse_encode(self.paths, serializer);
    }
}

impl SseEncode for crate::api::svg::SvgScene {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f32>::sse_encode(self.width, serializer);
        <f32>::sse_encode(self.height, serializer);
        <Vec<crate::api::svg::SvgPath>>::sse_encode(self.paths, serializer);
        <Vec<crate::api::svg::SvgImage>>::sse_encode(self.images, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
